Add chunk encoding for float histogram
prometheus/prometheus pull request #11716
Opened 2022-12-14 11:22 UTC by codesome

This PR adds a new chunk encoding for the float histogram. This is a prerequisite to test out https://github.com/prometheus/prometheus/pull/11522/ (it includes some work from that PR for the chunk). @marctc and I decided it is best to have it as a separate PR for easy review.

2022-12-14 12:47 UTC, beorn7 commented
On my review queue…

2022-12-14 18:39 UTC, beorn7 requested changes
Looks great in general. But found some things to comment upon. :)

2022-12-14 18:39 UTC, beorn7 commented on tsdb/chunkenc/float_histogram.go
> +	// copy them.
Perhaps mention here that we can always recycle the slices for leading and trailing bits as they are never returned to the caller.

2022-12-14 18:39 UTC, beorn7 commented on tsdb/chunkenc/histogram_meta.go
> +			if deltas {
The code comment above needs an update for the delta==false case.

2022-12-14 18:47 UTC, beorn7 commented
To reiterate: I think we should handle the gauge histogram case later (see detailed comments above). Let's first get the float histogram (for counter-like float histograms) done, and then think about the gauge histogram case (without counter resets, with disappearing buckets, and such), as this needs to be solved for integer histograms, too.

Another thing we can think about later: If a `FloatHistogram` is effectively an integer histogram (because all the floats in it can be represented by ints), we can store it more efficiently as a normal (integer) `Histogram`. However, this adds the complication that we need to re-encode or at least start a new chunk if suddenly the next histogram for the same series is an "actual" `FloatHistogram`. This optimization could be done behind the scenes, or we can "leave it to the caller", i.e. implement it in the ingestion part. This deserves some thought, as we should probably do the same thing for conventional float samples. Many of those are effectively integers and could be stored much more efficiently. That's true for something like request counters but even more so for the many many time series that are always 1 or always 0, or those that are either 1 or 0. (For those, we could introduce even more efficient RLE like encodings, see #10275 .) All of this is out of scope of this PR, of course. I just mention it to justify why we don't want to do this kind of optimization right here.

2022-12-15 13:00 UTC, codesome commented on tsdb/chunkenc/float_histogram.go
> +		bucketsMissing = true
Bucket missing is as good as a counter reset, so I guess you mean only a name change here while adding counter reset logic everywhere.

2022-12-15 13:18 UTC, codesome commented on tsdb/chunkenc/float_histogram.go
> +
For it to be efficient, it cannot be generics :/
The "oldBuckets" slice for the FloatHistogram is []xorValue and not []float64, and creating a new slice for this check everytime will be inefficient.

2022-12-15 13:26 UTC, codesome commented on tsdb/chunkenc/float_histogram.go
> +	it.pBucketsLeading, it.pBucketsTrailing, it.nBucketsLeading, it.nBucketsTrailing = nil, nil, nil, nil
I don't know in depth how these are used, so I will take your word for it.

2022-12-15 13:33 UTC, codesome commented on tsdb/chunkenc/float_histogram.go
> +					trailing: 0xff,
No idea. Will remove it.

2022-12-15 13:33 UTC, codesome commented on tsdb/chunkenc/float_histogram.go
> +					trailing: 0xff,
No idea. Will remove it.

2022-12-15 13:46 UTC, codesome commented on tsdb/chunkenc/float_histogram_test.go
> +func TestFloatHistogramChunkSameBuckets(t *testing.T) {
Good point! I switched to the improved tests and already found bugs

2022-12-19 13:53 UTC, beorn7 commented on tsdb/chunkenc/float_histogram.go
> +
Too bad. But thanks for catching.

2022-12-19 14:58 UTC, beorn7 approved these changes
Looks correct and complete to me now. @marctc if you have anything to add, please let us know.

2022-12-20 10:03 UTC, merged