Handle more arithmetic operators for native histograms
prometheus/prometheus pull request #12262
Opened 2023-04-13 18:39 UTC by zenador

Addresses https://github.com/prometheus/prometheus/issues/12250

Works when manually testing on the UI with scalars and float metrics, but need to add more unit tests. This also does not fix the query sharding issue yet (but it changes the result to another wrong one, so looks like there are more bugs there).

2023-04-24 11:11 UTC, krajorama commented on promql/engine.go
> +		if hlhs != nil && hrhs == nil && rhs != 0 {
I think we can probably allow rhs==0 and let it recover like the float series case

2023-05-11 17:09 UTC, beorn7 requested changes
Looks great. Just some not-so-substantial comments.

Special thanks for the testing. This should be much easier once #11170 is done.

Two other things to do:
1. Amend the documentation to explain what works now.
2. I think we can/should also fix other aggregation operators (stddev etc.). Some of them can be made work with histograms, others should ignore them cleanly (currently, we count them, which might throw some results off).

I think (1) needs to be included in this PR, but (2) can be done in a separate PR.

2023-05-11 17:09 UTC, beorn7 commented on promql/engine.go
> +					break
I'm not sure if that additional check here is really helping. The case of mixed aggregations should be very rare. By adding this check here, we are creating overhead for the common case and get just a bit of performance back for the rare error case.

2023-05-11 17:09 UTC, beorn7 commented on promql/engine.go
> +					break
Again, I don't think this condition is beneficial in the big picture.

2023-05-11 18:39 UTC, zenador commented
Besides what you mentioned, noticed a few more issues:
- `Mul` is an exact duplicate of `Scale` which is used for `rate`. Removed `Mul`. Please let me know if you prefer to rename all the `Scale`s to `Mul` or something.
- When adding, subtracting, and aggregating, we do not compact the histogram, ending up with ugly redundant buckets (but this problem doesn't happen with sum/avg_over_time, so we had a lot of redundancy in `TestNativeHistogram_Sum_Count_Add_AvgOperator`, with some expected histograms compacted and some not. I added the compact step to fix that, but not sure if this is unnecessary overhead if we don't actually care if the result is compacted.

2023-05-11 20:35 UTC, beorn7 commented
Good catch with the `Scale` vs `Mul`. Now that we have `Div` and `Add` and `Sub`, maybe we should call `Scale` `Mul` indeed.

I'll get to the other points ASAP.

2023-05-16 19:09 UTC, beorn7 approved these changes
Thank you very much. That's a huge chunk of work done.

I hope it's OK if I squash the 14 commits into one.

2023-05-16 19:15 UTC, merged