Perform integer/float histogram type checking on conversions
prometheus/prometheus pull request #12272
Opened 2023-04-18 17:31 UTC by zenador

Currently the conversion methods from prompb.Histogram to histogram.(Float)Histogram do not check the type of histogram, and leaves it to the caller to enforce, which can cause errors that are hard to debug (especially since `HistogramProtoToFloatHistogram` has changed behaviour in recent commits without changing method name or signature - it used to take float histograms as input and now it takes integer histograms) and will result in invalid histograms where the spans do not match the buckets. It's up to the maintainers to decide if it's worth the overhead of checking or if you prefer to leave it to the caller.

2023-04-20 14:56 UTC, beorn7 requested changes
Sorry for the confusion caused by the renaming. It was my idea (because the old names were somewhat inconsistent). I like the checks. If they turn out to be too expensive, we can still think of something else.

Just a few nits about comments and the text message in the panic.

2023-04-20 14:56 UTC, beorn7 commented on storage/remote/codec.go
> +// provided proto message.
I would leave the old comment in here, because the caller still has to make sure. Maybe add "Otherwise, the function panics."

2023-04-20 14:56 UTC, beorn7 commented on storage/remote/codec.go
> +		panic("don't call HistogramProtoToHistogram on a float histogram")
Minor nit: I think we usually state what went wrong in the panic. In this case, that would be more like "HistogramProtoToHistogram called with a float histogram".

2023-04-20 14:56 UTC, beorn7 commented on storage/remote/codec.go
> +// provided proto message to a Float Histogram.
See above.

2023-04-20 14:56 UTC, beorn7 commented on storage/remote/codec.go
> +		panic("don't call FloatHistogramProtoToFloatHistogram on an integer histogram")
See above.

2023-04-20 14:56 UTC, beorn7 commented on storage/remote/codec.go
> +// to a float histogram.
See above.

2023-04-20 14:56 UTC, beorn7 commented on storage/remote/codec.go
> +		panic("don't call HistogramProtoToFloatHistogram on a float histogram")
See above.

2023-04-21 19:51 UTC, beorn7 approved these changes
Thank you very much. (And apologies for delays on other PR reviews – still busy at KubeCon.)

2023-04-21 19:52 UTC, merged

2023-04-21 19:54 UTC, zenador commented
Thank you! No hurry :)