fix(scrape/manager): reload manager's internals with new function
prometheus/prometheus pull request #13017
Opened 2023-10-22 02:56 UTC by hainenber

Add a new function, `ApplyConfigAndOptions`, to allow external parties to reload scrape managers.

2023-10-22 03:43 UTC, hainenber commented
Refactored to remove deprecated `enable_protobuf_negotiation` option

2023-10-22 05:59 UTC, roidelapluie requested changes
I prefer not to have this as these options should only be changed at startup time. You can just create a new manager if you need to change them.

2024-08-27 11:24 UTC, bboreham commented
Hello from the bug-scrub!  Do you think you will come back to this @hainenber , or shall we just close it?

2024-08-27 11:26 UTC, hainenber commented
You can go ahead and close it. Unlikely I'll have time continuing.

2025-02-25 11:07 UTC, closed without merging