add-checksum-makefile
prometheus/prometheus pull request #13328
Opened 2023-12-24 01:38 UTC by kylewin

Add File Checksum

Signed-off-by: Kyle Nguyen <nvietthu@gmail.com>

2023-12-25 08:13 UTC, SuperQ requested changes
This is still vulnerable to the same MitM claim, as downloading the checksums can be faked.

2023-12-25 08:41 UTC, kylewin commented
> as downloading the checksums can be faked
I'd love to know your suggestion for this. I don't think we will put all the checksum into the repo, I mean to hardcode the checksum ?

2023-12-25 09:28 UTC, kylewin commented
And I don't understand why downloading an original checksum file from a https link still can be faked ?

2023-12-25 09:34 UTC, SuperQ commented
I personally question the assertion about the MitM in the first place. If https can be faked, all bets are off.

2023-12-25 09:40 UTC, kylewin commented
> If https can be faked, all bets are off.

I'm expecting a broken Cert will appear if MitM happens. If someone can even fake Github certs, that's a big Sec leak for Github. In my opinion, Github provides the link for checksum.txt and it's ok to use it

Anw, I'd love to know your ideas for this

2023-12-27 09:41 UTC, roidelapluie commented
> > If https can be faked, all bets are off.
> 
> I'm expecting a broken Cert will appear if MitM happens. If someone can even fake Github certs, that's a big Sec leak for Github. In my opinion, Github provides the link for checksum.txt and it's ok to use it
> 
> Anw, I'd love to know your ideas for this

Then why do we need the checksum ? We also download promu with https on github/

2023-12-27 10:09 UTC, kylewin commented
> Then why do we need the checksum ? We also download promu with https on github
So why Github Release put the checksum there ?

Im here to contribute. Please read my these comments:
[1](https://github.com/prometheus/prometheus/pull/13328#issuecomment-1868891836) - "Anw, I'd love to know your ideas for this" << This is the most essential. If you have a better idea, I welcome and willing to follow
[2](https://github.com/prometheus/prometheus/pull/13328#issuecomment-1868859635) - "I don't think we will put all the checksum into the repo, I mean to hardcode the checksum ?"

2024-08-13 11:31 UTC, bboreham commented
Hello from the bug-scrub!  I see there has been some debate on this in the past.

In the meeting, we agreed:
* Checking the checksum is valid.
* The checksums to be checked should be hard-coded into Prometheus code, e.g. beside where the version is specified ("`PROMU_VERSION ?= 0.15.0`").
* The operations should be: download the file, check the checksum, use the file.  This PR currently checks one download then does another one, which is vulnerable to sophisticated attackers giving different responses to the two downloads.

2025-02-18 11:42 UTC, bboreham commented
Hello again from the bug-scrub!
No update in 6 months, so we will close this.  The issue remains open, if someone wants to come back to it.

2025-02-18 11:42 UTC, closed without merging