[WIP] prometheus support parse exemplars from native histogram
prometheus/prometheus pull request #13488
Opened 2024-01-29 05:28 UTC by fatsheep9146

prometheus support parse exemplars from native histogram

2024-02-01 16:23 UTC, beorn7 commented
I assume this is still WIP? (You said so in the title, but didn't submit it as WIP. And tests are still failing.)

2024-02-01 16:24 UTC, beorn7 commented
I have converted the PR to a draft. Please mark it as "ready for review" as appropriate.

2024-02-02 05:16 UTC, fatsheep9146 commented
> I have converted the PR to a draft. Please mark it as "ready for review" as appropriate.

Thanks, this pr is still in progress. @beorn7

2024-02-08 13:06 UTC, beorn7 requested changes
Thank you very much. Looks good code-wise, just some comments about doc comments and tests.

2024-02-08 13:06 UTC, beorn7 commented on model/textparse/protobufparse_test.go
> +	>
In different news, could you add one more exemplar with a timestamp at the end to test if multiple exemplars are parsed fine and if they are also parsed after an exemplar without a timestamp?

2024-02-11 12:25 UTC, fatsheep9146 commented on model/textparse/protobufparse.go
> +	exemaplerPos int
Done

2024-02-11 12:25 UTC, fatsheep9146 commented on model/textparse/protobufparse.go
> +		if !isClassic && len(m.GetHistogram().GetExemplars()) > 0 {
Done

2024-02-13 19:11 UTC, beorn7 commented
On my list…

2024-02-14 15:10 UTC, beorn7 approved these changes
There are a few more word-smithing nits, but I'll commit them directly.

Thank you very much.

2024-02-14 15:10 UTC, beorn7 commented on model/textparse/protobufparse.go
> +	// exemplarPos is the position within exemplars slice of native exemplars.
```suggestion
	// exemplarPos is the position within the exemplars slice of a native histogram.
```

2024-02-14 15:10 UTC, beorn7 commented on model/textparse/protobufparse.go
> +// If this field is empty, the legacy bucket section is still used for exemplars.
```suggestion
// histogram, the exemplars in the native histogram will be returned.
// If this field is empty, the classic bucket section is still used for exemplars.
```

2024-02-14 16:24 UTC, merged