Update histogram math
prometheus/prometheus pull request #13680
Opened 2024-03-01 12:15 UTC by Maniktherana

Addresses #11269 
Bucket count is now represented by area rather than height

Height is now = `count / range`, creating a height proportional to frequency density

@beorn7

2024-03-01 12:17 UTC, Maniktherana commented
https://github.com/prometheus/prometheus/assets/14011425/653cd2a6-07df-403a-b55f-28e919339eb8

2024-03-01 16:14 UTC, beorn7 commented
Great stuff. I'll have a detailed look ASAP (which might be Tuesday). Thank you very much.

2024-03-05 17:09 UTC, beorn7 commented
Sorry, drowning in work, it will take another day or so.

2024-03-07 19:32 UTC, beorn7 commented
I'm playing with this now. It looks generally very nice, but there seem to be some quirks.

Here my observations (really just as an outside observer, without any insight into the code, as I'm not familiar with React):

The text version is sorted fine now and displays the zero bucket just fine, too.

In the graphical version, the zero bucket is displayed, but "left of zero", while it should be centered on zero (it would probably be fine to only display the half "right of zero" if there are no negative buckets):
![image](https://github.com/prometheus/prometheus/assets/5609886/14800452-54c8-46ca-9977-15c10c2d06b6)
(You can see the little tick mark for zero between the bar and the popup.)

With the normalization of the height of the buckets, the number next to the Y axis appear pretty useless. Maybe we can just omit them? Showing the count in the bucket seems to be a fine way. (And there is always the text representation underneath for precise numbers and for those that cannot hover the mouse pointer for accessibility reasons.)

Speaking of the height of the bars, they seem off. See the following two screenshots:
![image](https://github.com/prometheus/prometheus/assets/5609886/34808a72-bc22-4548-97cd-05368efd9320)
![image](https://github.com/prometheus/prometheus/assets/5609886/a2d79d16-05b7-4635-a2f9-46db5106e623)

The 1st one highlights a bucket with 44 observations, the 2nd one a bucket with 82 buckets. The numbers are also displayed in the some way in the text part. However, the bucket with count of 44 is _higher_ than the bucket with a count of 82. It should be the other way round, and that by a lot (almost factor 2). Remember, with the exponential rendering, all buckets have the same width in the rendering, so their height should be proportional to their count (because ultimately the area of each bar has to be proportional to the count). So there is effectively no normalization necessary (you could even display the counts directly on the y axis.)

I haven't checked the linear plot in detail yet. Let's first get the exponential plot right. However, I can say that [this example app](https://github.com/prometheus/client_golang/blob/main/examples/random/main.go) creates a normal distribution of observations. So the linear plot should result in a nice Gauss bell shape. Maybe that's even working, if squinting at 
![image](https://github.com/prometheus/prometheus/assets/5609886/60926082-a5b9-405e-928c-cb6d75f21c4e)

But as said, let's take care of it once the exponential plot works.

Another note for the zero bucket: By default, it is very narrow (and it could be set to a width of zero in some use cases). That means that the normalization for the linear plot would result in an extreme height (or even infinity in case of a zero width zero bucket). There should be some limitation on the displayed height of the zero bucket, maybe something like "display it if it is at most 10x higher than the highest other bucket, but just cut it off at the max height of any other bucket otherwise". When I deliberately put observations in a zero bucket with the narrow default width, I see an overly high bucket even in the exponential plot, which tells me that some normalisation is happening (but it should not, see above):
![image](https://github.com/prometheus/prometheus/assets/5609886/4af83390-5d92-44f1-9203-72a6882529a7)

And here the funny result with a zero bucket of width zero that actually contains a few observations of exactly zero:

![image](https://github.com/prometheus/prometheus/assets/5609886/1015e023-727e-48be-9178-97f944ac597b)

Final topic: gaps between buckets. There can be gaps between buckets (or in other word: empty buckets, that just aren't explicitly stated in the query result, because native histograms are "sparse"), and they seem to be displayed nicely in the linear view, but they aren't displayed at all in the exponential view. I think they should. Imagine the gaps are filled with buckets of population zero and following the same exponential bucketing schema. (A more subtle topic is the possible gap between the zero bucket and the first regular bucket, but it's probably fine to not draw this one, at least not in the exponential plot.)

Sorry for all the comments. The zero bucket is really a beast to plot because it breaks the regularity. So I would propose the following plan:
- Let's first get the height of the bars solved in the exponential view.
- Then let's get the gaps between buckets right in the exponential view.
- Then let's figure out how to render the zero bucket properly.
- And finally we can find out if the height in the linear plot is correct.

2024-03-07 20:13 UTC, juliusv commented
(@beorn7 Side note: I never had the expectation that the area under each bar in the exponential view had to be adjusted to be proportional to the number of observations and was surprised to hear that. Is that a commonly expected thing when displaying exponetial histograms on an exponential axis? If we didn't do that, then the Y-axis would keep making sense...)

2024-03-07 20:29 UTC, beorn7 commented
https://en.wikipedia.org/wiki/Histogram#/media/File:Travel_time_histogram_total_n_Stata.png is the proverbial histogram from Wikipedia . Note the unit on the y axis (people per time interval).

2024-03-08 03:56 UTC, Maniktherana commented
> With the normalization of the height of the buckets, the number next to the Y axis appear pretty useless. Maybe we can just omit them?

Yes I'll remove them. One of your screenshots show the scales to be in the order of trillion ^ 2 😆 which doesn't seem useful.

> In the graphical version, the zero bucket is displayed, but "left of zero", while it should be centered on zero:

this could be fixed by simply updating the position of the 0 tick:
```
 const zeroAxisLeft =
    scale === 'linear'
      ? ((0 - rangeMin) / (rangeMax - rangeMin)) * 100 + '%'
      : (closestToZero.closestIdx / (buckets ? buckets.length : 1)) * 100 + '%';
```

On an exponential scale, it finds the bucket closest to zero and puts the 0 marker on that bucket's lower bounds. I'll fix this and put the 0 tick on true zero.

 > (it would probably be fine to only display the half "right of zero" if there are no negative buckets)

This bit is accounted for

```
{rangeMin < 0 && <div style={{ position: 'absolute', left: zeroAxisLeft }}>0</div>}
```

> The 1st one highlights a bucket with 44 observations, the 2nd one a bucket with 82 buckets. The numbers are also displayed in the some way in the text part. However, the bucket with count of 44 is higher than the bucket with a count of 82. It should be the other way round, and that by a lot (almost factor 2). Remember, with the exponential rendering, all buckets have the same width in the rendering, so their height should be proportional to their count (because ultimately the area of each bar has to be proportional to the count). So there is effectively no normalization necessary (you could even display the counts directly on the y axis.)

Okay so for this one, I made the assumption that these are frequency density histograms. This means that the height is is calculated by `count / range` (frequency density). I went ahead with this as on multiplying the height with the width, we'd end up with an area that represents the actual count. *This means that height is proportional to frequency density, not height*.

So if we went ahead an calculated the heights for the buckets you mentioned, you'd see that they're actually consistent:
```
44 / (0.000030517578125 - 0.0000152587890625) = 28,83,584
82 / (0.00006103515625 - 0.000030517578125) = 26,86,976
```
here, bucket with count 44 is actually taller than that with count 82.

Now this begs the question: _On an exponential scale each bucket has the same width, so shouldn't height be proportional to count?_

This is a valid question, here's my rationale: Yes the widths do appear the equal to eachother, but they are on an exponential scale. Because they are on the exponential scale, this would mean if we calculate the width of some bucket _x_ on the linear scale, it would have the same value as bucket _x_ on the exponential scale. The values are the same, they simply appear differently on each scale.

Because of this, the formula to calculate the height remains the same on both scales `(height = count/range)`.

Do let me know if there are gaps in my theory.

> Then let's get the gaps between buckets right in the exponential view

Hmm, yes I'll try and figure something out for this.

> However, I can say that [this example app](https://github.com/prometheus/client_golang/blob/main/examples/random/main.go) creates a normal distribution of observations. So the linear plot should result in a nice Gauss bell shape. Maybe that's even working, if squinting at

That's the same example I'm using. Question tho (my statistics is fuzzy), are these random values supposed to fit exactly in a bell curve on linear scales? or should it simply look somewhat like a bell curve. I belive it would then act somewhat like a [galton board](https://en.wikipedia.org/wiki/Galton_board). Again, do let me know if I'm wrong.

2024-03-13 15:51 UTC, beorn7 commented
Sorry for the delay in my response.

Let's clarify the scaling of the height of the buckets first:

I think the linear case is pretty clear, and your implementation might be correct already. In the linear case, I think we should not have values on the Y axis, as they will generally be weird to read and understand. The hover info will tell the user about the number of observations in the bucket, and that's good enough. I do believe that, within statistical noise, the graphical appearance of the the histogram in linear view should approach a Gaussian bell curve.

_But_ let's do a final verification of all of that once we have nailed the exponential view, because the latter will be the one that users are using normally.

So now about the exponential view: What you use as input in your calculations is the range directly, but since we have a logarithmic x axis, you also need to take the logarithm of the range. If you do that, you'll find out that now everything cancels and the height of the buckets is proportional to the count in the bucket. That's only the case because the buckets are exponential. (Once custom bucket layouts land here, we have to revisit the rendering.) In other words: The actually displayed area of the bars (or the "numbers of pixels" in the bar) should be proportional to the count in the bucket. So for the current bucket schemas, the exponential view is very simple: height == count, and you can put the count on the y axis.
The only odd one out here is the zero bucket, because it doesn't comply with the logarithmic x axis (it would be infinitely far away from any bucket if we did the x axis logarithmic all the way). That's why you should just render the zero bucket as wide as all the other buckets and again make it's height == count.

Yet another comparison: Imagine a linear bucket layout (one bucket from 0 to 1, next from 1 to 2, next from 2 to 3). If you render such a histogram on a linear x axis, again height would be proportional to count. Exponential buckets rendered on a linear x axis need the multiplication math for their correct area, but if the x axis is logarithmic itself, it all cancels out and you are back to height being proportional to the count.

2024-03-17 15:10 UTC, beorn7 commented
Another thought: You could also do the multiplication thing in the exponential view "strictly correct" right now (I assume you have to change the current code just slightly to take into account the logarithmic nature of the x axis by doing an exponentiation at the right place). This will appear needlessly complicated for now, but will help once custom bucket definitions are a thing.

2024-03-28 11:00 UTC, Maniktherana commented
@beorn7 Again, sorry about the delay

I have now set height proportional to count for the exponential scale and kept everything same for linear. Also removed the y axis labels for linear.

<img width="558" alt="Screenshot 2024-03-28 at 4 00 15 PM" src="https://github.com/prometheus/prometheus/assets/14011425/a3ae31d5-9665-4f68-ac56-69431096d8a3">

<img width="564" alt="Screenshot 2024-03-28 at 4 00 22 PM" src="https://github.com/prometheus/prometheus/assets/14011425/d48e54dc-36ad-44e9-84bd-245865fd4324">

2024-03-28 13:26 UTC, beorn7 commented
Height looks good now.

The only thing left for exponential view is to position the bars correctly. I try to summarize our discussion we had on Slack:

I don't know a lot about how to code this all in CSS and Typescript etc., so I make a few fundamental assumption to create some pseudocode. Please fix my assumptions where necessary.

I assume the leftmost point on the x-axis in the rendering is 0 and the rightmost point is 1 (maybe it's something like 0% to 100%, but formulating it in terms of 0 to 1 is easier below).

The "standard bucket width" `bw` is defined as
```
bw := abs(log(abs(upper_bound_of_any_bucket)) - log(abs(lower_bound_of_any_bucket)))
```

This should yield the same result, no matter what bucket you pick, as long as you don't pick the zero bucket. (Note: There is the special case where _only_ the zero bucket is populated, which has to be rendered just as a single bar centered on zero.)

Every bucket will be rendered with this width `bw`.

What's left is to map bucket boundaries to points on the x axis. For that, let's define the following values:
```
start_neg := log(abs(lower_bound_of_lowest_negative_bucket))
end_neg := log(abs(upper_bound_of_highest_negative_bucket))
start_pos := log(lower_bound_of_lowest_positive_bucket))
end_pos := log(upper_bound_of_highest_positive_bucket))
width_neg := end_neg - start_neg
width_pos := end_pos - start_pos
width_total := width_neg + bw + width_pos
```

Now it's easy to calculate the position of bucket boundaries etc. on that 0 to 1 scale for the whole panel:
- The zero mark is at `( width_neg + 0.5 * bw ) / width_total`
- The zero bucket starts at `( width_neg ) / width_total`
- The zero bucket ends at `( width_neg + bw ) / width_total`
- Any boundary of a negative bucket is it `(log(abs(boundary)) - start_neg) / width_total`
- Any boundary of a positive bucket is it `(log(boundary) - start_pos + bw + width_neg) / width_total`

2024-03-28 13:30 UTC, beorn7 commented
Note that the above always puts the zero bucket directly adjacent to the highest negative bucket and the lowest positive bucket, no matter if there is a gap in between. I think that's fine (as in most cases there will be a gap anyway, and it might be more confusing to show it than to gloss over it), but we can revisit that decision if needed.

2024-05-14 11:42 UTC, bboreham commented
Hello from the bug-scrub!  Do you think you will come back to this @Maniktherana ?

2024-05-14 12:06 UTC, Maniktherana commented
> Hello from the bug-scrub!  Do you think you will come back to this @Maniktherana ?

Hey there, yes I'm working on it now 😬

2024-05-15 16:48 UTC, beorn7 requested changes
What happens with these changes? (I haven't tried myself… :duck:)

2024-05-15 16:48 UTC, beorn7 commented on web/ui/react-app/src/pages/graph/HistogramChart.tsx
> +  const startNegative = buckets ? Math.log(Math.abs(minNegative)) : 0; //start_neg
Let's do the following like in my latest update:

```suggestion
  const startNegative = buckets ? -Math.log(Math.abs(minNegative)) : 0; //start_neg
```

2024-05-15 16:48 UTC, beorn7 commented on web/ui/react-app/src/pages/graph/HistogramChart.tsx
> +  const endNegative = buckets ? Math.log(Math.abs(maxNegative)) : 0; //end_neg
```suggestion
  const endNegative = buckets ? -Math.log(Math.abs(maxNegative)) : 0; //end_neg
```

2024-05-15 16:48 UTC, beorn7 commented on web/ui/react-app/src/pages/graph/HistogramChart.tsx
> +  const widthNegative = startNegative - endNegative; //width_neg
With the changes above, this becomes again the more intuitive:

```suggestion
  const widthNegative = endNegative - startNegative; //width_neg
```

2024-05-15 16:48 UTC, beorn7 commented on web/ui/react-app/src/pages/graph/HistogramChart.tsx
> +          Math.log(Math.abs(parseFloat(buckets[buckets.length - 1][1])))
If there are _only_ negative buckets, or even _only_ a zero bucket, this will break (just a note for the final code).

2024-05-15 16:48 UTC, beorn7 commented on web/ui/react-app/src/pages/graph/HistogramChart.tsx
> +            ? (Math.log(Math.abs(left)) - startNegative / widthTotal) * 100 + '%' // negative buckets boundary
With recent updates and fixed parenthesis:

```suggestion
            ? -(Math.log(Math.abs(left)) - startNegative) / widthTotal * 100 + '%' // negative buckets boundary
```

2024-05-15 16:48 UTC, beorn7 commented on web/ui/react-app/src/pages/graph/HistogramChart.tsx
> +            : (Math.log(left) - startPositive + bw + widthNegative / widthTotal) * 100 + '%'; // positive buckets boundary
```suggestion
            : (Math.log(left) - startPositive + bw + widthNegative) / widthTotal * 100 + '%'; // positive buckets boundary
```

2024-05-15 17:19 UTC, Maniktherana commented
> What happens with these changes? (I haven't tried myself… 🦆)

getting closer
negative buckets are now appearing on the chart
the leftmost bucket is at `left: 55.5556%; width: 2.77778%;`


<img width="657" alt="Screenshot 2024-05-15 at 10 48 12 PM" src="https://github.com/prometheus/prometheus/assets/14011425/0201520d-7e45-4e53-8fe8-f8e440199660">

2024-05-15 17:27 UTC, Maniktherana commented
Apologies, missed the last suggested change. changing the formula for positive buckets boundary is having this weird effect where negative buckets are  overflowing to the right.

<img width="636" alt="Screenshot 2024-05-15 at 10 52 27 PM" src="https://github.com/prometheus/prometheus/assets/14011425/6df0f92d-ff0d-4af6-9943-8b35e7d91a1d">

https://github.com/prometheus/prometheus/assets/14011425/9e0feeb1-189a-4a4e-aea7-53793ecf2c75

2024-05-16 12:26 UTC, Maniktherana commented
In this last case, are they truly of different width or are they overlapping?

2024-05-16 12:35 UTC, beorn7 requested changes

2024-05-16 12:35 UTC, beorn7 commented on web/ui/react-app/src/pages/graph/HistogramChart.tsx
> +  const maxNegative = buckets ? parseFloat(buckets[closestToZero.closestIdx - 1][2]) : 0;
If the zero bucket is not populated, it isn't included in the buckets list, so the closestIdx ± 1 will fail.

2024-05-16 12:35 UTC, beorn7 commented on web/ui/react-app/src/pages/graph/HistogramChart.tsx
> +    return { closest, closestIdx };
You are not really using the returned `closest`, are you?

I think this should instead return the index of the closest-to-zero negative bucket and the index of the closest-to-zero positive bucket separately, so you don't need the ±1 magic above (which fails if there is no zero bucket in `buckets`).

2024-05-16 12:35 UTC, beorn7 commented on web/ui/react-app/src/pages/graph/HistogramChart.tsx
> +  function findClosestToZero(numbers: number[]): closestToZeroType {
I suspect you need to pass in the full buckets (or the upper limit for the negative buckets and the lower limit for the positive buckets), and you must not get confused by the zero bucket (which might or might not exist).

2024-05-16 12:37 UTC, beorn7 commented
> In this last case, are they truly of different width or are they overlapping?

They are truly different width. Buckets are never really overlapping.

> Also looks like the zero bucket goes from negative to positive ranges. Don't think that one is explicitly handled

Yes, that's the very definition of the zero bucket (it goes from positive to negative, or it is just zero with zero width).

2024-05-16 12:39 UTC, beorn7 commented
Another idea for `findClosestToZero`: Let it just find the zero bucket (the one that goes from negative to positive), and return its lower and upper limit. If there is no zero bucket, or its width is zero, just return `{0, 0}`. Then the other parts of the math should just work, and you would even render a possible gap between the zero bucket and the first positive/negative bucket correctly. (The name of the function should then be changed, maybe to `findZeroBucket`).

2024-05-16 13:20 UTC, Maniktherana commented
> > In this last case, are they truly of different width or are they overlapping?
> 
> They are truly different width. Buckets are never really overlapping.

<img width="1110" alt="Screenshot 2024-05-16 at 6 47 11 PM" src="https://github.com/prometheus/prometheus/assets/14011425/fdaa4100-25e0-4eb6-b9c0-75ac2767c9f9">

In the case I'm getting, they're overlapping. It can be verified on inspecting the element. Not sure in which case a bucketWidth may change as we're passing a single source of truth defined from the parent component (that is, `bw` and `width_total` are defined once and supplied to all buckets). Still, I'll try to see if I get a case where the bucket widths aren't equal

2024-05-16 14:02 UTC, Maniktherana commented
Another interesting observation: if there are a certain amount of buckets, for example 20, then we get `bw = 100/20 = 5%`. And this is expected

however, for cases like where number of buckets = 7, we should be getting `bw = 100/7 = 14.28%` or so but I'm getting `16.6667%`. And I believe this also affects the left positioning for buckets around and including the zero bucket.

<img width="1318" alt="Screenshot 2024-05-16 at 7 32 05 PM" src="https://github.com/prometheus/prometheus/assets/14011425/b344bbf4-1db1-48e7-bc8b-3149a8076041">

2024-05-16 14:06 UTC, beorn7 commented
WRT overlapping zero bucket: If you look at the numbers in your screenshot above, you'll see that no buckets are overlapping.

This is a "feature" of the zero bucket. If you set it such that it doesn't coincide with the "natural" bucket boundary of the neighboring buckets, those buckets are cut short, and that's the one case where you get smaller buckets with an otherwise standard exponential schema.

There are custom buckets in the making, and those will have variable bucket length anyway. So eventually, we have to handle them. Right now, we can ignore it for now, but we need to get that special case around the zero bucket solved. I think with the formulas developed so far, it should "just work", and the artifacts we see are caused by some implementation problems.

2024-05-16 14:09 UTC, Maniktherana commented
> WRT overlapping zero bucket: If you look at the numbers in your screenshot above, you'll see that no buckets are overlapping.

I'm not saying that the ranges of buckets are overlapping. I mean on the chart itself they are physically overlapping. the middle one has 2 buckets. and on the console to the right you'll see 2 elements have the same `left` position

<img width="1278" alt="Screenshot 2024-05-16 at 7 37 12 PM" src="https://github.com/prometheus/prometheus/assets/14011425/6b778e4f-9974-4e7f-ad81-2b1e01690215">

2024-05-16 14:11 UTC, beorn7 commented
Yes, and I think that needs to be fixed (and it's unexpected from the math).

2024-05-16 14:16 UTC, Maniktherana commented
> Yes, and I think that needs to be fixed (and it's unexpected from the math).

I played around a bit and found that updating this nudged it in the right direction:
```diff
-const widthTotal = widthNegative + expBucketWidth + widthPositive; //width_total
+const widthTotal = widthNegative + 3 * expBucketWidth + widthPositive; //width_total
```

2024-05-16 15:04 UTC, beorn7 commented
But isn't that just ad-hoc compensation for a mistake that we have done elsewhere?

I think with a fixed closestToZero, based on the bounds of the zero bucket, things should all fall into place nicely.

2024-05-16 16:08 UTC, Maniktherana commented
> But isn't that just ad-hoc compensation for a mistake that we have done elsewhere?
> 
> I think with a fixed closestToZero, based on the bounds of the zero bucket, things should all fall into place nicely.

You are correct. I also believe the same when it comes to positioning the buckets. Zero bucket calculation might also be affecting the widths

2024-05-29 09:23 UTC, Maniktherana commented
@beorn7 updated some calculations:
 - `minPositive` and `maxNegative` now use zero bucket's index if available
 - Updated zero marker position
 - if zero bucket exists, it is positioned at `(width_neg) / width_total`

It fixes some things but but theres still the issue of these overlapped buckets:

<img width="681" alt="Screenshot 2024-05-29 at 2 43 20 PM" src="https://github.com/prometheus/prometheus/assets/14011425/f30da930-46dd-47c5-853f-7476c2c3978a">

but in some cases, theres no such issue:
<img width="829" alt="Screenshot 2024-05-29 at 2 50 54 PM" src="https://github.com/prometheus/prometheus/assets/14011425/ae2df8cd-cc59-4c7b-bbfe-08a1c6898160">

finally, sometimes a bucket may have ranges with very small boundaries (order of 10^8 or so) and such buckets seem to occupy random positions. in this case, the highlighted bucket should be the right side of the zero marker: 

<img width="639" alt="Screenshot 2024-05-29 at 2 51 28 PM" src="https://github.com/prometheus/prometheus/assets/14011425/b79a84c4-5d9c-42cd-a457-36ee8db2eff3">

2024-05-30 18:47 UTC, beorn7 commented
At first glance, I would say your first screenshot is already the correct behavior. Maybe we should do the "frequency density thing" in that case, but maybe not. A zero bucket overlapping with the neighboring buckets is a scenario that should be avoided generally, and I'm not sure there is a good way of treating it graphically. I will look at the details ASAP to come to a conclusion (which will be early next week, hopefully).

I will also look into the issue with the last screenshot then. Floating point precision issues are probably hard to avoid in certain situations, and maybe they even play out a bit differently in the Javascript VM than in a native program… However, 1e-8 isn't _that_ small in terms of IEEE 754. As said, I'll try to get to the bottom of it.

And if anyone beats me to it before the start of next week, even better.

2024-05-31 06:33 UTC, Maniktherana commented
> At first glance, I would say your first screenshot is already the correct behavior. Maybe we should do the "frequency density thing" in that case, but maybe not. A zero bucket overlapping with the neighboring buckets is a scenario that should be avoided generally, and I'm not sure there is a good way of treating it graphically. I will look at the details ASAP to come to a conclusion (which will be early next week, hopefully).

We made the assumption that once we calculate `bw` for one bucket, it would be the same width for each of the bars. Now excluding the zero bucket (as thats a sepcial case) I found out that the buckets adjascent to the zero bucket in the first screenshot actually don't have the same bucket width as the rest of the bars. And you are correct, that screenshot is graphically correct if we calculate `bw` for each of the buckets (except zero bucket).

So I went ahead and calculated the true `bw` for all buckets (except zero bucket) and this is what I got:
<img width="654" alt="Screenshot 2024-05-31 at 12 01 09 PM" src="https://github.com/prometheus/prometheus/assets/14011425/a55aa657-c032-4d47-ab52-9a5c695cbddc">


Its the same as the first screenshot, only now the buckets dont overlap in the HTML

2024-06-06 12:53 UTC, beorn7 commented
I think we are almost there. I haven't done a code-level check, just tried out a few things, and I have run into a few edge cases:

If I create a histogram with only positive buckets (which is by far the most common case), the left-most bucket is extending into the negative:
![image](https://github.com/prometheus/prometheus/assets/5609886/4c074864-01cb-46a3-83e3-4524f5d67f11)

I could imagine an off-by-one error because there are no negative bucket and/or because there is no zero bucket. I suspect that is easy to fix.

What's worse is if there _is_ a zero bucket plus positive buckets but no negative buckets. Nothing is rendered then, and this is what I see in the console:
![image](https://github.com/prometheus/prometheus/assets/5609886/6d336bf4-f2d2-4300-8aa6-976b39e8d6c0)

I have also looked at the linear representation. It looks good at first glance, with the only quirk that the zero bucket isn't centered:

![image](https://github.com/prometheus/prometheus/assets/5609886/dbbd6c56-c266-4818-8f48-2ea06934f768)

With different resolution, I can even see the zero bucket being so far off center that it is somewhere in the middle of other buckets.

2024-06-07 07:38 UTC, Maniktherana commented
> I think we are almost there. I haven't done a code-level check, just tried out a few things, and I have run into a few edge cases:
> 
> If I create a histogram with only positive buckets (which is by far the most common case), the left-most bucket is extending into the negative: ![image](https://private-user-images.githubusercontent.com/5609886/337267228-4c074864-01cb-46a3-83e3-4524f5d67f11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NDI0OTEsIm5iZiI6MTcxNzc0MjE5MSwicGF0aCI6Ii81NjA5ODg2LzMzNzI2NzIyOC00YzA3NDg2NC0wMWNiLTQ2YTMtODNlMy00NTI0ZjVkNjdmMTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDdUMDYzNjMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTJhMzJlNWQ3YjFhMTdhMThlMThjMTg3NjkyN2UyN2NhZmI0OTQ4ZjU0NTRkY2IyMWE1ZTVhZTJlYjljYjIyOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aIavKzBhNzk_xC05I7zj1mEcFrlcUFMldDyLCcXQDss)
> 
> I could imagine an off-by-one error because there are no negative bucket and/or because there is no zero bucket. I suspect that is easy to fix.

I've figured out that the issue here is that `widthNegative` isn't zero when there's only positive buckets. So have to tweak `startNegative` or `endNegative` and whatever is being used to calculate them


> What's worse is if there _is_ a zero bucket plus positive buckets but no negative buckets. Nothing is rendered then, and this is what I see in the console: ![image](https://private-user-images.githubusercontent.com/5609886/337270321-6d336bf4-f2d2-4300-8aa6-976b39e8d6c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NDI0OTEsIm5iZiI6MTcxNzc0MjE5MSwicGF0aCI6Ii81NjA5ODg2LzMzNzI3MDMyMS02ZDMzNmJmNC1mMmQyLTQzMDAtOGFhNi05NzZiMzllOGQ2YzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDdUMDYzNjMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGI5MWM1N2I0ZWM1YmIzMDVhMjRiOTY2NDE3OGVmYTM3ZGNlMmRhYWE3NDQ2NjRjNGRlNWZmMDJjNGYxZjBkOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Jx9RguzqNQbaGa18SR56s0GBfljEyIbgCgL2QH1bPeA)

will investigate this


> I have also looked at the linear representation. It looks good at first glance, with the only quirk that the zero bucket isn't centered:
> 
> ![image](https://private-user-images.githubusercontent.com/5609886/337259625-dbbd6c56-c266-4818-8f48-2ea06934f768.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NDI0OTEsIm5iZiI6MTcxNzc0MjE5MSwicGF0aCI6Ii81NjA5ODg2LzMzNzI1OTYyNS1kYmJkNmM1Ni1jMjY2LTQ4MTgtOGY0OC0yZWEwNjkzNGY3NjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDdUMDYzNjMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGU2N2RkOTQ5YzNkY2IwNDhhYmRiZjY0MzAzODM3ZWNlNWQ3ZGMyNmVmNGY5M2NiNTAwYWFlY2IzYWUzZjI4OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tSuZcPPFz-zUNSXOnsfuO-9SlheYYIpAkcTFLftQ8ws)
> 
> With different resolution, I can even see the zero bucket being so far off center that it is somewhere in the middle of other buckets.

Fixed this including an issue where zero axis would be in the middle of the first positive bucket if a zero bucket wasnt available

2024-06-07 08:11 UTC, Maniktherana commented
> I've figured out that the issue here is that widthNegative isn't zero when there's only positive buckets. So have to tweak startNegative or endNegative and whatever is being used to calculate them

fixed calculations for `maxPositive`, `minPositive`, 'minNegative` and `maxNegative`

2024-06-13 14:55 UTC, beorn7 commented
My next round of trying out…

Only positive buckets, no zero buckets, looks good now, both exponential and linear.

Positive buckets plus zero bucket renders fine in linear view, but looks like the following in exponential view (i.e. no visible bars, although the grid seems to be dimensioned right):
![image](https://github.com/prometheus/prometheus/assets/5609886/e8707b96-e928-4ae7-ae9e-51b7f5bd287e)

Negative buckets plus zero bucket renders fine in linear view, but looks like the following in exponential view (maybe this helps to explain the problems with positive + zero bucket - bars might be shifted off-grid):
![image](https://github.com/prometheus/prometheus/assets/5609886/c5922b3a-d09e-452c-ba61-1122e105108d)

2024-06-13 15:05 UTC, Maniktherana commented
This is very interesting as I had accounted for zero bucket and only positive/negative buckets

Can you please share the console output if you have it

2024-06-13 15:32 UTC, beorn7 commented
Maybe it's best if you reproduce this kind of rendering on your side so that you can iterate on it more quickly.

I used my usual example program, i.e. https://github.com/prometheus/client_golang/blob/main/examples/random/main.go , and simply added `NativeHistogramZeroThreshold: 0.00001,` after line 66 to create the zero bucket for sure, and then changed line 110 to `v := math.Abs((rand.NormFloat64() * *normDomain) + *normMean)` to only get positive observations.

2024-06-13 15:37 UTC, beorn7 commented
Here is a bit of the console output (it's a lot, another reason you better reproduce it locally):

```
ID bucket-0-48-13800 
 left 0.0005806675366224224 
 right 0.0006332224387944383 
 count 138 
 bucketWidth -1.2345679012345585% 
 bucketLeft 106.17283950617282% 
 bw 0.0866433975699934 
 widthTotal -6.931471805599453 
 widthNegative -11.512925464970229 
 startPositive -11.512925464970229 rangeMax 0.0008955117609420616 rangeMin -0.00001
main.56ca8c23.js:2 bucket-0-49-6300 EXPbucketleftPOS= ( -7.364688793449419 - -11.512925464970229 + 0.0866433975699934 + -11.512925464970229 )/( -6.931471805599453 )= 104.93827160493827%
main.56ca8c23.js:2 ID bucket-0-49-6300 
 left 0.0006332224387944383 
 right 0.0006905339660024878 
 count 63 
 bucketWidth -1.2345679012345712% 
 bucketLeft 104.93827160493827% 
 bw 0.0866433975699934 
 widthTotal -6.931471805599453 
 widthNegative -11.512925464970229 
 startPositive -11.512925464970229 rangeMax 0.0008955117609420616 rangeMin -0.00001
main.56ca8c23.js:2 bucket-0-50-2600 EXPbucketleftPOS= ( -7.278045395879426 - -11.512925464970229 + 0.0866433975699934 + -11.512925464970229 )/( -6.931471805599453 )= 103.7037037037037%
main.56ca8c23.js:2 ID bucket-0-50-2600 
 left 0.0006905339660024878 
 right 0.0007530326295937211 
 count 26 
 bucketWidth -1.2345679012345712% 
 bucketLeft 103.7037037037037% 
 bw 0.0866433975699934 
 widthTotal -6.931471805599453 
 widthNegative -11.512925464970229 
 startPositive -11.512925464970229 rangeMax 0.0008955117609420616 rangeMin -0.00001
main.56ca8c23.js:2 bucket-0-51-800 EXPbucketleftPOS= ( -7.191401998309432 - -11.512925464970229 + 0.0866433975699934 + -11.512925464970229 )/( -6.931471805599453 )= 102.46913580246913%
main.56ca8c23.js:2 ID bucket-0-51-800 
 left 0.0007530326295937211 
 right 0.0008211879055212055 
 count 8 
 bucketWidth -1.2345679012345585% 
 bucketLeft 102.46913580246913% 
 bw 0.0866433975699934 
 widthTotal -6.931471805599453 
 widthNegative -11.512925464970229 
 startPositive -11.512925464970229 rangeMax 0.0008955117609420616 rangeMin -0.00001
main.56ca8c23.js:2 bucket-0-52-400 EXPbucketleftPOS= ( -7.10475860073944 - -11.512925464970229 + 0.0866433975699934 + -11.512925464970229 )/( -6.931471805599453 )= 101.23456790123457%
main.56ca8c23.js:2 ID bucket-0-52-400 
 left 0.0008211879055212055 
 right 0.0008955117609420616 
 count 4 
 bucketWidth -1.2345679012345712% 
 bucketLeft 101.23456790123457% 
 bw 0.0866433975699934 
 widthTotal -6.931471805599453 
 widthNegative -11.512925464970229 
 startPositive -11.512925464970229 rangeMax 0.0008955117609420616 rangeMin -0.00001
```

2024-06-13 15:56 UTC, Maniktherana commented
Weird, bucketwidth and width total are negative

2024-06-18 18:03 UTC, beorn7 commented
Are you able to reproduce this situation in your local setup?

2024-06-19 08:29 UTC, Maniktherana commented
> Are you able to reproduce this situation in your local setup?

Yes, getting the same result. also rebased on top of master

2024-06-19 09:00 UTC, Maniktherana commented
@beorn7 
The issue was being caused by incorrect implementations of `findMinPositive` `findMaxNegative` functions i made. Pushed some changes for it but there may be some edge cases left. This is what the graphs look like for only negative + zero bucket


<img width="646" alt="Screenshot 2024-06-19 at 2 28 40 PM" src="https://github.com/prometheus/prometheus/assets/14011425/eabdffe5-fb38-4c22-a8f6-c0055429c4fc">

and only positive + zero bucket:
<img width="652" alt="Screenshot 2024-06-19 at 2 29 36 PM" src="https://github.com/prometheus/prometheus/assets/14011425/5104c772-ca12-4c75-9f2d-0dad557fb03e">

interestingly the width is zero for the zero bucket in the first image. is this expected?

2024-06-20 16:52 UTC, beorn7 commented
BTW: For linear rendering, everything looks fine.

2024-06-20 17:08 UTC, beorn7 commented
I found an interesting edge case with the currently checked in code. This is for a zero bucket with zero width and actually some samples in it:

![image](https://github.com/prometheus/prometheus/assets/5609886/8b214f39-5507-430b-8342-ad8a0404e41f)

Everything works fine if the zero-width zero bucket is entirely missing, but here things get wildly out of control. You see multiple buckets overlaying, and the ranging is completely off.

I have pushed my example target to another branch so that you can easily reproduce the behavior locally: https://github.com/prometheus/client_golang/blob/beorn7/play/examples/random/main.go

(Note the separate observations with value 0 in lines 110 to 118.)

The zero-width zero bucket with observations in it looks like this in the list:
![image](https://github.com/prometheus/prometheus/assets/5609886/2eb9ac86-67fd-4ddd-a973-d3c461c86e38)

I hope that will give you a hint what's going wrong.

2024-06-20 17:14 UTC, beorn7 commented
Interestingly, the case of "zero width zero bucket" is handled fine if there are only positive buckets in addition to the zero bucket. But if there are only negative buckets plus the zero bucket, it behaves weirdly, as well is if there are both positive and negative buckets and the zero bucket.

2024-06-26 04:35 UTC, Maniktherana commented
I've managed to fix the issue here but in the same case the linear plot looks off.

<img width="638" alt="Screenshot 2024-06-26 at 10 00 24 AM" src="https://github.com/prometheus/prometheus/assets/14011425/47dbe9b7-9ac0-4f78-9046-af004d1e732c">

Now everything is flat with a very big jump
<img width="622" alt="Screenshot 2024-06-26 at 10 01 37 AM" src="https://github.com/prometheus/prometheus/assets/14011425/569e708f-cf4a-4d84-9cc1-fcf19a370545">

might have something to do with how fds are being calculated

2024-06-26 16:37 UTC, beorn7 commented
> Not sure what we should do in this case in terms of how we want to render a zero-width zero bucket.

Frankly, I would just _not_ render them in the linear view, as they have zero width.

2024-06-26 17:33 UTC, Maniktherana commented
<img width="607" alt="Screenshot 2024-06-26 at 10 55 03 PM" src="https://github.com/prometheus/prometheus/assets/14011425/9363fced-4915-461f-adbc-002e16eb726a">
<img width="609" alt="Screenshot 2024-06-26 at 11 01 53 PM" src="https://github.com/prometheus/prometheus/assets/14011425/3ef8f15a-b7bd-4068-bfb3-a3e62d928abe">

Zero bucket is rendered but its left position, width and height are all zero now. Essentially its not visible in the graph

I'll see if I can skip rendering it from the dom entirely but I'm not sure if its possible

2024-06-27 11:35 UTC, beorn7 commented
From my frontend-illiterate perspective, I don't care if it is just not rendered or actually removed from the DOM. I'm playing with this now to see if I can find another hole.

2024-06-27 13:20 UTC, beorn7 commented
The scenario with a zero-width zero bucket and otherwise only negative buckets results in this exponential view:
![image](https://github.com/prometheus/prometheus/assets/5609886/9b7dcc98-18de-4b73-a2c1-09064240e4a4)

This is weird because in exponential view, all buckets should have the same apparent width.

2024-06-27 13:25 UTC, beorn7 commented
I guess it has something to do with switching from exponential to linear and back.

If I freshly load the exponential view, I see things going wrong in a different way:
![image](https://github.com/prometheus/prometheus/assets/5609886/f8ce7aee-72ec-4086-a2ee-b5c318e43af5)

If I then switch to linear view, I see a linear view that looks fine (as far as I can say).

If I then switch back to exponential view, I get the weird variable bucket width as shown in the previous comment.

2024-06-27 13:26 UTC, beorn7 commented
If I have only negative buckets without a zero-width zero bucket, everything works fine.

2024-06-27 13:36 UTC, beorn7 commented
Everything else seems to work, so the weird behavior above really only happens with only negative buckets plus a zero-width zero bucket.

2024-06-27 14:13 UTC, Maniktherana commented
> This is weird because in exponential view, all buckets should have the same apparent width.

this may have something to do with: https://github.com/prometheus/prometheus/pull/13680#issuecomment-2141320997

2024-06-28 16:00 UTC, juliusv reviewed
I took a look from the UI code side, and of course it's hard to exactly follow all the intricate logic, so I trust that Björn and you have done a lot of testing around that :) Other than that, it looks pretty good, and I only have a few nits as comments.

Thanks for all the effort of making all the weird corner cases work!

2024-06-28 17:15 UTC, Maniktherana commented on web/ui/react-app/src/pages/graph/HistogramChart.tsx
> +  const fdMax = fds.reduce((a, b) => Math.max(a, b));
I actually didn't know you can do `Math.max(...arr)` until now 😅
that should be more performant honestly
there's also `Math.max.apply(Math, arr)` that seems to be even more performant!

reduce does seem unnecessary so I'll get rid of it

2024-06-28 17:15 UTC, Maniktherana commented on web/ui/react-app/src/pages/graph/HistogramChart.tsx
> +    if (width === 0) {
This is actually the most recent edge case we've been working on. I'm not sure on the specifics of how you can go about defining a bucket with range [-0, 0] but @beorn7 did manage to create it in one of the client_golang examples: https://github.com/prometheus/prometheus/pull/13680#issuecomment-2181162457

So it is a case that may happen, but I'm not sure how often one would encounter it.

I'll try adding some comments explaining this

2024-06-28 17:17 UTC, Maniktherana commented on web/ui/react-app/src/pages/graph/HistogramChart.tsx
> +  const countMax = buckets.map((b) => parseFloat(b[3])).reduce((a, b) => Math.max(a, b));
As above, probably don't need `reduce()` as we can use `Math.max` directly
I'll see if I can combine these two

2024-06-28 17:17 UTC, Maniktherana commented on web/ui/react-app/src/pages/graph/HistogramChart.tsx
> +  if (!buckets) {
yes possibly should do `!buckets || buckets.length === 0`

2024-06-28 17:18 UTC, Maniktherana commented on web/ui/react-app/src/pages/graph/HistogramHelpers.ts
> +  console.log('findmaxneg returning: ', buckets[buckets.length - 1][2]);
Quite a few broken stuff + log statements were pushed while trying to patch things

Will remove

2024-06-28 17:20 UTC, Maniktherana commented on web/ui/react-app/src/types/types.ts
> +export type ScaleType = 'linear' | 'exponential';
Noted, I'll move it back

2024-06-28 17:23 UTC, Maniktherana commented on web/ui/react-app/src/pages/graph/HistogramChart.tsx
> +          {buckets && (
Good catch! I'll get rid of it

2024-06-28 17:59 UTC, juliusv commented on web/ui/react-app/src/pages/graph/HistogramChart.tsx
> +  const fdMax = fds.reduce((a, b) => Math.max(a, b));
Hah! Spreading an array creates a copy of the array, so your reduce approach is indeed more performant (at least ChatGPT seems to think so as well: https://chatgpt.com/share/90355166-0f79-4f7e-8371-71c1df5d577e) - I just don't think it makes a huge difference in this case.

2024-06-28 18:11 UTC, Maniktherana commented on web/ui/react-app/src/pages/graph/HistogramChart.tsx
> +  const fdMax = fds.reduce((a, b) => Math.max(a, b));
I also found this: https://www.measurethat.net/Benchmarks/Show/21316/1/array-mathmax-vs-for-loop

2024-06-28 18:17 UTC, juliusv commented on web/ui/react-app/src/pages/graph/HistogramChart.tsx
> +  const fdMax = fds.reduce((a, b) => Math.max(a, b));
Wow, ok weird! I wonder why the for loop is so slow in there (at least for me in Chrome). Maybe the first two options are just more optimized/optimizeable under the hood.

![image](https://github.com/prometheus/prometheus/assets/538008/f4a5d3df-8f2e-4635-b90c-09b577871b20)

![image](https://github.com/prometheus/prometheus/assets/538008/8408af83-6b27-4225-979f-a37963c81fa5)

Well, I guess just do the spread with `Math.max()` then in any case, it's fast and the most normal-looking :)

2024-06-28 18:25 UTC, Maniktherana commented on web/ui/react-app/src/pages/graph/HistogramChart.tsx
> +  const fdMax = fds.reduce((a, b) => Math.max(a, b));
Apparently chrome will say `Math.max.apply` is fastest with ~800k-1m+ ops/s and `for loop` will have 8k ops/s

but on firefox the results literally invert with `Math.max.apply` being the slowest so what even is performance 🤷‍♂️

2024-06-28 19:41 UTC, juliusv commented on web/ui/react-app/src/pages/graph/HistogramChart.tsx
> +  const fdMax = fds.reduce((a, b) => Math.max(a, b));
Wow, crazy. Didn't know the two browsers had such different optimizations. But yeah, just go with the spread max then :)

2024-06-29 10:44 UTC, beorn7 commented
General remark about the zero-width zero bucket: It's not "effectively disabling it". It is a valid use case where you only want observations of precisely zero to go into the zero bucket

2024-06-29 10:49 UTC, juliusv commented
> General remark about the zero-width zero bucket: It's not "effectively disabling it". It is a valid use case where you only want observations of precisely zero to go into the zero bucket

Ah yes, makes sense!

2024-06-30 09:40 UTC, Maniktherana commented
I fixed the issue of all negative + zero-width zero bucket
I also tried to see if I can render the zero bucket in exponential view but I can't seem to figure out a good way to do so when its only negative/positive + [0,0]. So I've removed it from rendering in exponential view too

Here's the results for negative + [0,0]:
<img width="607" alt="Screenshot 2024-06-30 at 3 09 07 PM" src="https://github.com/prometheus/prometheus/assets/14011425/ad419bc8-d822-42b7-b7fa-c02916e1da0c">
<img width="612" alt="Screenshot 2024-06-30 at 3 09 13 PM" src="https://github.com/prometheus/prometheus/assets/14011425/4e2bdebb-ef1c-4571-ac8c-67afdb736d02">

Also applied @juliusv suggestions (I've left in some console logs tho)

2024-07-02 14:41 UTC, juliusv commented
Thanks! @beorn7 things look good to me from the UI code side, so I'll leave the merging up to you depending on whether you're satisfied :)

2024-07-02 17:11 UTC, beorn7 commented
Thank you very much. I will have a look ASAP.

2024-07-04 11:59 UTC, beorn7 approved these changes
Now everything seems to work. Thank you very much everyone for all your efforts to get this right.

2024-07-04 12:01 UTC, merged

2024-07-19 11:03 UTC, bboreham commented
What is a good changelog message for this change?

2024-07-19 12:59 UTC, Maniktherana commented
how about:

[ENHANCEMENT] UI (experimental native histograms): Update the math behind native histogram table view for accurate representation #13658

2024-07-19 14:54 UTC, bboreham commented
The audience for this is administrators installing Prometheus; I can't imagine they know much about the math.

how about:

[ENHANCEMENT] UI (experimental native histograms): more accurate representation https://github.com/prometheus/prometheus/pull/13658

2024-07-19 15:18 UTC, Maniktherana commented
sounds good!