tsdb/index: Refactor Reader tests
prometheus/prometheus pull request #14071
Opened 2024-05-09 09:31 UTC by aknuds1

Refactor `tsdb/index.Reader` tests, as they have a lot in common. Pulled out of #13620, as the refactor became irrelevant there :)

2024-05-15 15:01 UTC, beorn7 requested changes
LGTM. Just a comment style suggestion, and of course, merge conflicts…

2024-05-15 18:52 UTC, aknuds1 commented
Thanks for the review @beorn7 - I fixed the merge conflicts (and refactored `TestReader_PostingsForLabelMatchingHonorsContextCancel` to use `createFileReader`), and applied your suggestion. PTAL :)

2024-05-16 09:50 UTC, beorn7 approved these changes

2024-05-16 09:50 UTC, beorn7 commented
Thank you, will merge now.

2024-05-16 09:51 UTC, merged