Use clean host header for scraping request
prometheus/prometheus pull request #14203
Opened 2024-06-04 04:02 UTC by jonathan-anyword

2024-06-04 09:15 UTC, jonathan-anyword commented
This change is not solving the issue, it seems that it how the http lib in Go is working.
I'll check with them

2024-06-10 22:08 UTC, bboreham requested changes
Since you don't seem sure about the fix, I'll change this to draft.

2024-06-10 22:08 UTC, bboreham commented on scrape/scrape.go
> +		hostname := strings.Split(req.URL.Host, ":")[0]
Prefer https://pkg.go.dev/net#SplitHostPort, which will work with IPv6 addresses.

2025-01-07 11:40 UTC, bboreham commented
Hello from the bug-scrub!  No update in 7 months so closing.
If you would like to come back to it, please comment here and we can re-open.
Thanks!

2025-01-07 11:40 UTC, closed without merging