Split warnings and info annotations in API response
prometheus/prometheus pull request #14327
Opened 2024-06-20 14:53 UTC by zenador

Addresses https://github.com/prometheus/prometheus/issues/14135

2024-06-20 17:06 UTC, bboreham submitted a review, later dismissed
This change lgtm.

The existing implementation by which `errors.Is(err, PromQLInfo)` is working seems a bit tricksy to me; better done via Go types.

2024-06-26 15:52 UTC, beorn7 commented
> The existing implementation by which `errors.Is(err, PromQLInfo)` is working seems a bit tricksy to me; better done via Go types.

I guess this was my idea, seduced by the convenience of using `fmt.Errorf` with `%w`. It could be changed to a different approach, but obviously not as part of this PR.

2024-06-26 16:03 UTC, beorn7 requested changes
Thank you very much. Looks good in general. I just have a number of ideas about naming. See individual comments.

2024-06-26 16:03 UTC, beorn7 commented on util/annotations/annotations.go
> +		infoArr = append(infoArr, fmt.Sprintf("%d more info messages omitted", infoSkipped))
messages → annotations

But we should stay consistent in any case, so either change the message in L120 to "%d more warning annotations omitted", or keep L120 as is and change this into "%d more infos omitted". (But I get how the latter reads a bit weird. I would still be fine with it, as it is shorter. Your call.)

2024-06-26 16:03 UTC, beorn7 commented on web/api/v1/api.go
> +	Info      []string    `json:"info,omitempty"`
Maybe `Infos` for consistency?

2024-06-26 16:03 UTC, beorn7 commented on web/api/v1/api.go
> +		Info:     info,
I would definitely prefer `Infos` here. The context is clear, i.e. that this is a plural to mark that the value for this key is a list of strings.

2024-06-26 16:20 UTC, beorn7 commented
The [comment in lines 116 to 119](https://github.com/prometheus/prometheus/pull/14327/files#diff-d8edc673795ebafcce64036e85a031d0fd3d09cbcaea9bb1cc140373542afc92R116-R119) needs an update. (I cannot comment on unchanged lines directly, so I'm providing the link here.)

2024-07-03 10:57 UTC, zenador commented
@beorn7 PTAL

2024-07-03 16:49 UTC, beorn7 approved these changes
Looks good. Thank you.

Do you think you could add a "minimal UI change" to this PR? Like rendering the infos in the same way as the warnings, just in a slightly less alarming color. That would be an MVP we could merge, and then we could ask the UI experts to make it nicer later, like including a button to hide infos or something.

2024-07-05 20:26 UTC, zenador commented
@beorn7 Added the minimal UI change

2024-07-05 21:06 UTC, juliusv commented on web/ui/react-app/src/pages/graph/Panel.tsx
> +            <Col>{info && <Alert color="success">{info}</Alert>}</Col>
`success` is green, I'd pick `info` as the info-level color (blue/turquoise-ish):

```suggestion
            <Col>{info && <Alert color="info">{info}</Alert>}</Col>
```

2024-07-05 21:07 UTC, juliusv commented
UI change looks good to me besides the comment on the color.

2024-07-06 09:04 UTC, juliusv approved these changes
Thanks 👍

2024-07-06 09:05 UTC, merged