promql: Fix issue where summation of +/- infinity returns NaN instead of infinity
prometheus/prometheus pull request #14362
Opened 2024-06-28 01:24 UTC by charleskorn

This fixes an issue with `kahanSumInc` which would result it NaN being used as the final result when +Inf or -Inf was one of the values added.

I've expanded the test coverage of `kahanSumInc` to cover these cases and others involving NaN.

This does now mean that `kahanSumInc` does an extra check for Inf at each step. An alternative to this would be to check for +Inf or -Inf when computing the final result (ie. after all the calls to `kahanSumInc`), but I opted for this as the simplest, least invasive change given how widely `kahanSumInc` is used.

2024-06-30 14:58 UTC, codesome approved these changes

2024-06-30 15:03 UTC, codesome requested changes
Just 1 nit: Can we put the test inside functions_test.go? It is a small file and we can add a comment to the test saying why we are testing it separately.

2024-07-01 23:58 UTC, charleskorn commented
> Just 1 nit: Can we put the test inside functions_test.go? It is a small file and we can add a comment to the test saying why we are testing it separately.

That was my original intention, but `functions_test.go` is in the `promql_test` package, and so can't access `kahanSumInc`. 

`promql_test` was introduced in https://github.com/prometheus/prometheus/pull/13999. I can move the test to `functions_test.go`, but then I'll need to change its package back to `promql`.

2024-07-03 05:04 UTC, codesome approved these changes

2024-07-03 05:05 UTC, merged