Sync release-3.0 with main
prometheus/prometheus pull request #14369
Opened 2024-07-01 09:12 UTC by jan--f

Conflict resolution is detailed in the [merge commit](https://github.com/prometheus/prometheus/commit/c15c1d582b04ed4300a53a45f47691ead943ca04).

@krajorama @kofclubs @beorn7 Could you please check if I merged #13662 and #13904 correctly?

2024-07-02 08:52 UTC, beorn7 requested changes
I mostly trust the tests to make sure this is properly merged.

On that front, I have a tiny change in the tests to request.

2024-07-02 08:52 UTC, beorn7 commented on promql/promqltest/testdata/functions.test
> +eval_warn instant at 1m quantile_over_time(-1, data[1m])
This should stay at 2m, otherwise we are only touching one value.

2024-07-02 08:52 UTC, beorn7 commented on promql/promqltest/testdata/functions.test
> +eval_warn instant at 1m quantile_over_time(2, data[1m])
This should stay at 2m, otherwise we are only touching one value.

2024-07-02 08:52 UTC, beorn7 commented on promql/promqltest/testdata/functions.test
> +eval_warn instant at 1m (quantile_over_time(2, (data[1m])))
This should stay at 2m, otherwise we are only touching one value.

2024-07-03 07:51 UTC, jan--f commented
> On that front, I have a tiny change in the tests to request.

Thanks, fixed!

2024-07-03 11:33 UTC, merged