chore: migrate stale check to use stale github action
prometheus/prometheus pull request #14650
Opened 2024-08-09 17:29 UTC by electron0zero

stale check was added in https://github.com/prometheus/prometheus/pull/6826 using the https://github.com/probot/stale to label PRs with `stale` after 60 days of inactivity.

https://github.com/probot/stale is now deprecated and no longer maintained, and the repository archived since May 20, 2023.

They recommend migrating to [the stale action](https://github.com/actions/stale) instead.

This PR migrates the stale check and keeps the same behaviour as old stale workflow, and adds this file to `scripts/sync_repo_files.sh` so that it's synced to other repos.

also see https://github.com/prometheus/blackbox_exporter/pull/1170 for additional context on what prompted this migration.

2024-08-12 14:43 UTC, SuperQ requested changes

2024-08-12 14:43 UTC, SuperQ commented on .github/workflows/stale.yml
> +    - cron: '0 0 * * *'
Let's randomize this so it's not at midnight UTC.

```suggestion
    - cron: '16 22 * * *'
```

2024-08-12 14:45 UTC, SuperQ commented on .github/workflows/stale.yml
> +      - uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e
```suggestion
      - uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e # v9.0.0
```

2024-08-12 14:47 UTC, SuperQ commented on scripts/sync_repo_files.sh
> +SYNC_FILES="CODE_OF_CONDUCT.md LICENSE Makefile.common SECURITY.md .yamllint scripts/golangci-lint.yml .github/workflows/scorecards.yml .github/workflows/container_description.yml  .github/workflows/
```suggestion
SYNC_FILES="CODE_OF_CONDUCT.md LICENSE Makefile.common SECURITY.md .yamllint scripts/golangci-lint.yml .github/workflows/scorecards.yml .github/workflows/container_description.yml .github/workflows/stale.yml"
```

2024-08-12 14:48 UTC, SuperQ commented on .github/workflows/stale.yml
> +    if: github.repository_owner == 'prometheus'
This won't work with `prometheus-community`.

```suggestion
    if: github.repository_owner == 'prometheus' || github.repository_owner == 'prometheus-community' # Don't run this workflow on forks.
```

2024-08-12 18:08 UTC, electron0zero commented
@SuperQ added in the review suggestions. :)

2024-09-01 13:56 UTC, SuperQ approved these changes

2024-09-01 15:52 UTC, merged