[BUGFIX] PromQL: Fix behaviour of some aggregations with histograms
prometheus/prometheus pull request #15432
Opened 2024-11-20 21:31 UTC by NeerajGartia21

Part of #13934.

This PR fixes the behaviour of `topk`,`bottomk`, `limitk` and `limit_ratio` with histograms. The fixed behaviour are as follows:
- For `topk` and `bottomk` histograms are ignored and add info annotations added.
- For `limitk` and `limit_ratio` histograms are included in the results(if applicable).

I think we should wait for #15429 to test this PR better.

/CC: @beorn7 @charleskorn @krajorama

2024-11-21 17:27 UTC, beorn7 requested changes
Looks great. I literally only want some more periods at the end of sentences. ;)

2024-11-21 17:27 UTC, beorn7 commented on promql/engine.go
> +				// ignore histogram sample and add info annotation
Start sentence with a capital letter and end with a period.

2024-11-21 17:27 UTC, beorn7 commented on promql/promqltest/testdata/limit.test
> +# Exercise k==1 special case (as sample is added before the main series loop)
Now that you are fixing the typo, let's also add a period at the end.

2024-11-21 17:27 UTC, beorn7 commented on promql/promqltest/testdata/limit.test
> +# k==1: verify that histogram is included in the result
Period missing.

2024-11-21 19:11 UTC, NeerajGartia21 commented
Updated the PR!

2024-11-26 18:11 UTC, beorn7 approved these changes

2024-11-26 18:12 UTC, merged