[WIP] util: fix alignment of atomic uint64
prometheus/prometheus pull request #15548
Opened 2024-12-06 18:24 UTC by TinfoilSubmarine

Partially fixes https://github.com/prometheus/prometheus/issues/15547

2024-12-10 14:28 UTC, beorn7 requested changes
Thank you very much. See my comment. I hope that will fix the CI.

BTW: We want to address those glitches, see https://docs.google.com/document/d/1uurQCi5iVufhYHGlBZ8mJMK_freDFKPG0iYBQqJ9fvA/edit?pli=1&tab=t.0#bookmark=id.5ds2naruydu0

2024-12-10 14:28 UTC, beorn7 commented on model/histogram/test_utils.go
> +			Count:           uint64(uint64(i) + observationCount),
Th.e outer `uint64` isn't needed anymore.

2024-12-10 14:29 UTC, beorn7 commented
You also need to [sign the DCO](https://github.com/prometheus/prometheus/pull/15548/checks?check_run_id=34054654996).

2024-12-15 00:28 UTC, TinfoilSubmarine commented
The TestOOOHeadChunkReader_Chunk fix could probably be simplified, I just blindly swapped things to (u)int64 until there were no complaints and it fixed the test failure.

2024-12-15 22:54 UTC, TinfoilSubmarine commented
Simplified the TestOOOHeadChunkReader_Chunk test fix a little bit.

2024-12-18 14:48 UTC, beorn7 approved these changes
Thank you very much.

2024-12-18 14:48 UTC, beorn7 commented
Special thanks for the clean commit layout.

2024-12-18 14:49 UTC, merged