RELEASE.md: schedule 3.1 release
prometheus/prometheus pull request #15542
Opened 2024-12-05 15:41 UTC by jan--f

2024-12-09 17:27 UTC, beorn7 commented on RELEASE.md
> +| v3.1           | 2024-12-17                                 | **volunteer welcome**          |
How about this (based on various chats today):

```suggestion
| v3.1           | 2024-12-17                                 | Bryan Boreham (GitHub: @bboreham) |
| v3.2           | 2024-12-17                                 | Jan Fajerski (GitHub: @jan--f)   |
| v3.3           | 2024-12-17                                 | **volunteer welcome**          |
```

2024-12-09 18:09 UTC, beorn7 approved these changes
@bboreham should also approve, of course.

2024-12-09 18:09 UTC, beorn7 commented on RELEASE.md
> +| v3.2           | 2025-02-28                                 | Jan Fajerski (GitHub: @jan--f)    |
```suggestion
| v3.2           | 2025-01-28                                 | Jan Fajerski (GitHub: @jan--f)    |
```

2024-12-09 18:10 UTC, beorn7 requested changes
Detected a typo, see comment.

2024-12-09 18:46 UTC, beorn7 approved these changes
Of course, everyone being volunteered here needs to approve, too.

2024-12-09 18:57 UTC, machine424 approved these changes

2024-12-10 10:52 UTC, bboreham approved these changes

2024-12-10 10:52 UTC, merged