textparse: Optimized protobuf parser with custom streaming unmarshal.
prometheus/prometheus pull request #15731
Opened 2024-12-30 17:52 UTC by bwplotka

Fixes https://github.com/prometheus/prometheus/issues/14668

Depends on https://github.com/prometheus/prometheus/pull/15720

Previous attempts https://github.com/prometheus/prometheus/pull/15726 https://github.com/prometheus/prometheus/pull/15729

While it looks cumbersome to maintain, to make things efficient, one way or another we have to have streaming/lazy decoding with reusing of as much as possible. This does not depend on gogo we can do this on OpaqueAPI too but didn't want to change too much here. We could try to work with vtprotobuf or write our own plugin for those methods, but we can start by handcrafting now, this proto is not changing at all (if it will change in future, it will be OpenMetric proto likely).

2024-12-30 17:55 UTC, bwplotka commented
I have to fix tests etc, but initial benchmarks looks promising. There might be more to optimize here, didn't look on this iteration profile yet.

```
benchstat -filter="/fmt:PromProto" gogo=scrape-loop-v1.txt custom=scrape-loop-customdecode.txt
goos: darwin
goarch: arm64
pkg: github.com/prometheus/prometheus/scrape
cpu: Apple M1 Pro
                                 │    gogo     │               custom               │
                                 │   sec/op    │   sec/op     vs base               │
ScrapeLoopAppend/fmt=PromProto-2   54.48µ ± 8%   23.43µ ± 9%  -56.99% (p=0.002 n=6)

                                 │     gogo     │               custom                │
                                 │     B/op     │     B/op      vs base               │
ScrapeLoopAppend/fmt=PromProto-2   75.58Ki ± 1%   26.88Ki ± 6%  -64.44% (p=0.002 n=6)

                                 │    gogo    │              custom               │
                                 │ allocs/op  │ allocs/op   vs base               │
ScrapeLoopAppend/fmt=PromProto-2   810.0 ± 0%   123.0 ± 0%  -84.81% (p=0.002 n=6)
```

Now proto does not look too bad:

```
 benchstat -col /fmt  scrape-loop-customdecode.txt
goos: darwin
goarch: arm64
pkg: github.com/prometheus/prometheus/scrape
cpu: Apple M1 Pro
                   │  PromText   │              OMText               │             PromProto              │
                   │   sec/op    │   sec/op     vs base              │   sec/op     vs base               │
ScrapeLoopAppend-2   33.96µ ± 6%   30.88µ ± 3%  -9.08% (p=0.002 n=6)   23.43µ ± 9%  -31.01% (p=0.002 n=6)

                   │   PromText   │            OMText             │              PromProto              │
                   │     B/op     │     B/op      vs base         │     B/op      vs base               │
ScrapeLoopAppend-2   19.00Ki ± 7%   19.67Ki ± 6%  ~ (p=0.937 n=6)   26.88Ki ± 6%  +41.47% (p=0.002 n=6)

                   │  PromText  │              OMText              │              PromProto              │
                   │ allocs/op  │ allocs/op   vs base              │  allocs/op   vs base                │
ScrapeLoopAppend-2   12.00 ± 0%   13.00 ± 0%  +8.33% (p=0.002 n=6)   123.00 ± 0%  +925.00% (p=0.002 n=6)
```

2024-12-31 13:05 UTC, bwplotka commented on model/textparse/interface_test.go
> +	for i := range exp {
Will remove once I figure out fix for classic + native parsing

2025-01-14 14:15 UTC, bwplotka commented
Getting back to this after holidays...

2025-02-03 14:47 UTC, bwplotka commented
This should be now good to go 🎉 

cc @krajorama @beorn7 @bboreham 

Results looks solid. There's room for further allocation improvements, but I propose we iterate. Some of those needs interface updates.

```
$ benchstat append-v1.txt append-v2.txt 
goos: darwin
goarch: arm64
pkg: github.com/prometheus/prometheus/scrape
cpu: Apple M1 Pro
                                                     │ append-v1.txt │           append-v2.txt            │
                                                     │    sec/op     │   sec/op     vs base               │
ScrapeLoopAppend/data=1Fam1000Gauges/fmt=PromText-2     280.4µ ± 10%   283.9µ ± 8%        ~ (p=0.937 n=6)
ScrapeLoopAppend/data=1Fam1000Gauges/fmt=OMText-2       265.1µ ± 10%   271.7µ ± 7%        ~ (p=0.818 n=6)
ScrapeLoopAppend/data=1Fam1000Gauges/fmt=PromProto-2    447.0µ ±  2%   299.8µ ± 7%  -32.93% (p=0.002 n=6)
ScrapeLoopAppend/data=59FamsAllTypes/fmt=PromText-2     168.9µ ±  3%   168.6µ ± 2%        ~ (p=0.937 n=6)
ScrapeLoopAppend/data=59FamsAllTypes/fmt=OMText-2       166.4µ ±  1%   167.5µ ± 2%   +0.68% (p=0.041 n=6)
ScrapeLoopAppend/data=59FamsAllTypes/fmt=PromProto-2    159.0µ ±  3%   146.1µ ± 2%   -8.07% (p=0.002 n=6)
geomean                                                 230.1µ         213.8µ        -7.10%

                                                     │ append-v1.txt │            append-v2.txt            │
                                                     │     B/op      │     B/op      vs base               │
ScrapeLoopAppend/data=1Fam1000Gauges/fmt=PromText-2    178.7Ki ±  8%   182.3Ki ± 6%        ~ (p=0.240 n=6)
ScrapeLoopAppend/data=1Fam1000Gauges/fmt=OMText-2      170.5Ki ± 10%   172.3Ki ± 2%        ~ (p=0.937 n=6)
ScrapeLoopAppend/data=1Fam1000Gauges/fmt=PromProto-2   665.7Ki ±  2%   212.5Ki ± 3%  -68.08% (p=0.002 n=6)
ScrapeLoopAppend/data=59FamsAllTypes/fmt=PromText-2    74.02Ki ±  1%   73.53Ki ± 3%        ~ (p=0.589 n=6)
ScrapeLoopAppend/data=59FamsAllTypes/fmt=OMText-2      72.87Ki ±  1%   73.53Ki ± 3%        ~ (p=0.485 n=6)
ScrapeLoopAppend/data=59FamsAllTypes/fmt=PromProto-2   169.2Ki ±  1%   110.6Ki ± 5%  -34.62% (p=0.002 n=6)
geomean                                                162.6Ki         125.9Ki       -22.56%

                                                     │ append-v1.txt │            append-v2.txt            │
                                                     │   allocs/op   │ allocs/op   vs base                 │
ScrapeLoopAppend/data=1Fam1000Gauges/fmt=PromText-2       11.00 ± 0%   11.00 ± 0%        ~ (p=1.000 n=6) ¹
ScrapeLoopAppend/data=1Fam1000Gauges/fmt=OMText-2         12.00 ± 0%   12.00 ± 0%        ~ (p=1.000 n=6) ¹
ScrapeLoopAppend/data=1Fam1000Gauges/fmt=PromProto-2    8012.00 ± 0%   21.00 ± 0%  -99.74% (p=0.002 n=6)
ScrapeLoopAppend/data=59FamsAllTypes/fmt=PromText-2       18.00 ± 0%   18.00 ± 0%        ~ (p=1.000 n=6) ¹
ScrapeLoopAppend/data=59FamsAllTypes/fmt=OMText-2         19.00 ± 0%   19.00 ± 0%        ~ (p=1.000 n=6) ¹
ScrapeLoopAppend/data=59FamsAllTypes/fmt=PromProto-2     1693.0 ± 0%   642.0 ± 0%  -62.08% (p=0.002 n=6)
geomean                                                   92.15        29.11       -68.41%
¹ all samples are equal
```

2025-02-03 14:48 UTC, bwplotka commented on model/textparse/nhcbparse_test.go
> +test_histogram1_sum 0.0008280461746287094 1234568
I think the previous implementation of proto masked this bug in test data.

2025-02-04 18:50 UTC, GiedriusS commented on prompb/io/prometheus/client/decoder_test.go
> +	varintBuf := make([]byte, binary.MaxVarintLen32)
Maybe it would be more future-proof to test this against client_golang i.e. create a registry, add those metrics there, and simulate a protobuf scrape

2025-02-04 21:23 UTC, bwplotka commented on prompb/io/prometheus/client/decoder_test.go
> +	varintBuf := make([]byte, binary.MaxVarintLen32)
We do that in multiple places across Prometheus codebase e.g. textparse and scrape so I think we should be ok. WDYT?

2025-02-04 21:24 UTC, bwplotka commented on prompb/io/prometheus/client/decoder_test.go
> +	varintBuf := make([]byte, binary.MaxVarintLen32)
I also plan to someday write a protoc plugin for this so it's autogenerated.

2025-02-04 21:38 UTC, bwplotka commented
I have some ideas to optimize further (see https://pprof.me/14c6981f2f1f0ab8dce893729df1da67/?profileType=profile%253Aalloc_objects%253Acount%253Aspace%253Abytes&color_by=filename), but I will do those in the next iteration - this PR is already big.

2025-02-04 21:39 UTC, bwplotka commented
/prombench help

2025-02-04 21:40 UTC, bwplotka commented
/prombench main --bench.version=bench/protofirst

2025-02-04 22:02 UTC, bwplotka commented
/prombench cancel

2025-02-05 08:38 UTC, bwplotka commented
/prombench cancel

2025-02-05 08:55 UTC, bwplotka commented
Something got stuck (filled https://github.com/prometheus/test-infra/issues/831), retrying prombench

/prombench main --bench.version=bench/protofirst

2025-02-05 09:02 UTC, bwplotka commented
eh what a mess with our [testdata](https://github.com/prometheus/prometheus/blob/8d281c3491564738aab1f6735eea4542428d999f/model/textparse/testdata/promtestdata.txt) - just noticed it does not have histograms. So my microbenchmark does not include those. I will need to create a separate benchmark improvement PR and rebase this one it. :/  Might need to clean up textparse/testdata first.

2025-02-05 10:10 UTC, bwplotka commented
Prombench is dead at the moment https://github.com/prometheus/test-infra/issues/832

2025-02-05 10:10 UTC, bwplotka commented
/prombench cancel

2025-02-05 13:47 UTC, bwplotka commented
https://cloud-native.slack.com/archives/C01AUBA4PFE/p1738594684420579 @krajorama reported some problems when testing this PR, to be investigated

> I have 7000+ metrics, only ~300 reporting issues with duplicates timestamp different value

2025-02-07 08:41 UTC, krajorama requested changes

2025-02-07 08:41 UTC, krajorama commented on model/textparse/protobufparse.go
> +			if t == clientpb.MetricType_HISTOGRAM || t == clientpb.MetricType_GAUGE_HISTOGRAM &&
Missing paren makes histogram parsing fail:

```suggestion
			if (t == clientpb.MetricType_HISTOGRAM || t == clientpb.MetricType_GAUGE_HISTOGRAM) &&
```

2025-02-10 09:26 UTC, bwplotka commented
Rebased on top of https://github.com/prometheus/prometheus/pull/15998 for additional benchmark data

2025-02-10 09:37 UTC, bwplotka commented
Latest benchmarks:

```
benchstat v1.txt v2.txt 
goos: darwin
goarch: arm64
pkg: github.com/prometheus/prometheus/model/textparse
cpu: Apple M1 Pro
                 │   v1.txt    │               v2.txt               │
                 │   sec/op    │   sec/op     vs base               │
ParsePromProto-2   40.50µ ± 5%   28.89µ ± 2%  -28.66% (p=0.002 n=6)

                 │    v1.txt    │                v2.txt                │
                 │     B/s      │      B/s       vs base               │
ParsePromProto-2   90.55Mi ± 6%   126.92Mi ± 2%  +40.18% (p=0.002 n=6)

                 │    v1.txt    │               v2.txt                │
                 │     B/op     │     B/op      vs base               │
ParsePromProto-2   40.14Ki ± 0%   26.41Ki ± 0%  -34.20% (p=0.002 n=6)

                 │   v1.txt   │              v2.txt               │
                 │ allocs/op  │ allocs/op   vs base               │

```

```
benchstat -filter "/fmt:PromProto" append-v1.txt append-v2.txt
goos: darwin
goarch: arm64
pkg: github.com/prometheus/prometheus/scrape
cpu: Apple M1 Pro
                                                      │ append-v1.txt │            append-v2.txt            │
                                                      │    sec/op     │    sec/op     vs base               │
ScrapeLoopAppend/data=1Fam1000Gauges/fmt=PromProto-2      957.1µ ± 8%   607.2µ ±  5%  -36.56% (p=0.002 n=6)
ScrapeLoopAppend/data=237FamsAllTypes/fmt=PromProto-2     871.5µ ± 6%   813.9µ ± 11%   -6.61% (p=0.041 n=6)
geomean                                                   913.3µ        703.0µ        -23.03%

                                                      │ append-v1.txt │            append-v2.txt            │
                                                      │     B/op      │     B/op      vs base               │
ScrapeLoopAppend/data=1Fam1000Gauges/fmt=PromProto-2    1483.7Ki ± 1%   458.0Ki ± 6%  -69.13% (p=0.002 n=6)
ScrapeLoopAppend/data=237FamsAllTypes/fmt=PromProto-2    942.4Ki ± 0%   615.3Ki ± 3%  -34.71% (p=0.002 n=6)
geomean                                                  1.155Mi        530.9Ki       -55.11%

                                                      │ append-v1.txt │           append-v2.txt            │
                                                      │   allocs/op   │  allocs/op   vs base               │
ScrapeLoopAppend/data=1Fam1000Gauges/fmt=PromProto-2    16017.00 ± 0%    25.00 ± 4%  -99.84% (p=0.002 n=6)
ScrapeLoopAppend/data=237FamsAllTypes/fmt=PromProto-2     8.168k ± 0%   3.047k ± 0%  -62.70% (p=0.002 n=6)
geomean                                                   11.44k         276.0       -97.59%
```

Compared to other parsers now:

```
 benchstat -col /fmt  append-v2.txt 
goos: darwin
goarch: arm64
pkg: github.com/prometheus/prometheus/scrape
cpu: Apple M1 Pro
                                        │   PromText   │               OMText               │             PromProto              │
                                        │    sec/op    │    sec/op     vs base              │    sec/op     vs base              │
ScrapeLoopAppend/data=1Fam1000Gauges-2    594.5µ ± 29%   568.8µ ± 12%       ~ (p=0.485 n=6)   607.2µ ±  5%       ~ (p=0.699 n=6)
ScrapeLoopAppend/data=237FamsAllTypes-2   815.8µ ±  6%   887.3µ ±  4%  +8.77% (p=0.009 n=6)   813.9µ ± 11%       ~ (p=1.000 n=6)
geomean                                   696.4µ         710.4µ        +2.01%                 703.0µ        +0.95%

                                        │   PromText    │               OMText                │              PromProto              │
                                        │     B/op      │     B/op       vs base              │     B/op      vs base               │
ScrapeLoopAppend/data=1Fam1000Gauges-2    347.9Ki ±  3%   352.1Ki ±  8%       ~ (p=0.818 n=6)   458.0Ki ± 6%  +31.63% (p=0.002 n=6)
ScrapeLoopAppend/data=237FamsAllTypes-2   315.5Ki ± 12%   308.3Ki ± 10%       ~ (p=0.699 n=6)   615.3Ki ± 3%  +95.04% (p=0.002 n=6)
geomean                                   331.3Ki         329.5Ki        -0.54%                 530.9Ki       +60.23%

                                        │  PromText  │              OMText              │               PromProto                │
                                        │ allocs/op  │ allocs/op   vs base              │  allocs/op    vs base                  │
ScrapeLoopAppend/data=1Fam1000Gauges-2    13.00 ± 0%   13.50 ± 4%       ~ (p=0.182 n=6)     25.00 ± 4%     +92.31% (p=0.002 n=6)
ScrapeLoopAppend/data=237FamsAllTypes-2   14.00 ± 0%   15.00 ± 0%  +7.14% (p=0.002 n=6)   3047.00 ± 0%  +21664.29% (p=0.002 n=6)
geomean                                   13.49        14.23       +5.48%                   276.0        +1945.83%

```

2025-02-10 10:53 UTC, bwplotka commented
Ok, after reusing complex types and help bytes, I think it's good for this PR. We can optimize more later on, majority of this are labels.Labels and magic suffixes which might require protocol/parser interface redesign.

![image](https://github.com/user-attachments/assets/bb12e466-7c01-4e77-a1e3-8b54ba2fea42)

Final results:

```
 benchstat v1.txt v4.txt                           
goos: darwin
goarch: arm64
pkg: github.com/prometheus/prometheus/model/textparse
cpu: Apple M1 Pro
                 │   v1.txt    │               v4.txt               │
                 │   sec/op    │   sec/op     vs base               │
ParsePromProto-2   40.50µ ± 5%   26.22µ ± 3%  -35.26% (p=0.002 n=6)

                 │    v1.txt    │                v4.txt                │
                 │     B/s      │      B/s       vs base               │
ParsePromProto-2   90.55Mi ± 6%   139.87Mi ± 3%  +54.47% (p=0.002 n=6)

                 │    v1.txt    │               v4.txt                │
                 │     B/op     │     B/op      vs base               │
ParsePromProto-2   40.14Ki ± 0%   20.82Ki ± 0%  -48.12% (p=0.002 n=6)

                 │   v1.txt   │              v4.txt               │
                 │ allocs/op  │ allocs/op   vs base               │
ParsePromProto-2   870.0 ± 0%   465.0 ± 0%  -46.55% (p=0.002 n=6)
```

```
benchstat -filter "/fmt:PromProto" append-v1.txt append-v4.txt 
goos: darwin
goarch: arm64
pkg: github.com/prometheus/prometheus/scrape
cpu: Apple M1 Pro
                                                      │ append-v1.txt │            append-v4.txt            │
                                                      │    sec/op     │    sec/op     vs base               │
ScrapeLoopAppend/data=1Fam1000Gauges/fmt=PromProto-2      957.1µ ± 8%   572.6µ ± 10%  -40.17% (p=0.002 n=6)
ScrapeLoopAppend/data=237FamsAllTypes/fmt=PromProto-2     871.5µ ± 6%   733.0µ ±  4%  -15.89% (p=0.002 n=6)
geomean                                                   913.3µ        647.9µ        -29.06%

                                                      │ append-v1.txt │            append-v4.txt            │
                                                      │     B/op      │     B/op      vs base               │
ScrapeLoopAppend/data=1Fam1000Gauges/fmt=PromProto-2    1483.7Ki ± 1%   461.4Ki ± 5%  -68.90% (p=0.002 n=6)
ScrapeLoopAppend/data=237FamsAllTypes/fmt=PromProto-2    942.4Ki ± 0%   397.2Ki ± 4%  -57.85% (p=0.002 n=6)
geomean                                                  1.155Mi        428.1Ki       -63.80%

                                                      │ append-v1.txt │           append-v4.txt            │
                                                      │   allocs/op   │  allocs/op   vs base               │
ScrapeLoopAppend/data=1Fam1000Gauges/fmt=PromProto-2    16017.00 ± 0%    23.50 ± 2%  -99.85% (p=0.002 n=6)
ScrapeLoopAppend/data=237FamsAllTypes/fmt=PromProto-2     8.168k ± 0%   2.226k ± 0%  -72.75% (p=0.002 n=6)
geomean                                                   11.44k         228.7       -98.00%

```

Compared to other parsers now:
```
benchstat -col /fmt  append-v4.txt 
goos: darwin
goarch: arm64
pkg: github.com/prometheus/prometheus/scrape
cpu: Apple M1 Pro
                                        │   PromText   │               OMText               │             PromProto              │
                                        │    sec/op    │    sec/op     vs base              │    sec/op     vs base              │
ScrapeLoopAppend/data=1Fam1000Gauges-2    613.0µ ± 28%   585.2µ ± 10%  -4.54% (p=0.041 n=6)   572.6µ ± 10%  -6.59% (p=0.041 n=6)
ScrapeLoopAppend/data=237FamsAllTypes-2   780.1µ ±  4%   780.3µ ±  8%       ~ (p=0.818 n=6)   733.0µ ±  4%  -6.04% (p=0.009 n=6)
geomean                                   691.5µ         675.7µ        -2.29%                 647.9µ        -6.31%

                                        │   PromText    │               OMText                │              PromProto              │
                                        │     B/op      │     B/op       vs base              │     B/op      vs base               │
ScrapeLoopAppend/data=1Fam1000Gauges-2    341.4Ki ±  7%   354.8Ki ±  5%       ~ (p=0.394 n=6)   461.4Ki ± 5%  +35.15% (p=0.002 n=6)
ScrapeLoopAppend/data=237FamsAllTypes-2   311.9Ki ± 12%   319.2Ki ± 11%       ~ (p=0.485 n=6)   397.2Ki ± 4%  +27.36% (p=0.002 n=6)
geomean                                   326.3Ki         336.5Ki        +3.13%                 428.1Ki       +31.19%

                                        │  PromText  │              OMText              │               PromProto                │
                                        │ allocs/op  │ allocs/op   vs base              │  allocs/op    vs base                  │
ScrapeLoopAppend/data=1Fam1000Gauges-2    13.00 ± 8%   13.00 ± 8%       ~ (p=0.273 n=6)     23.50 ± 2%     +80.77% (p=0.002 n=6)
ScrapeLoopAppend/data=237FamsAllTypes-2   14.00 ± 0%   15.00 ± 0%  +7.14% (p=0.002 n=6)   2226.00 ± 0%  +15800.00% (p=0.002 n=6)
geomean                                   13.49        13.96       +3.51%                   228.7        +1595.36%

```

2025-02-10 12:29 UTC, bwplotka commented
@krajorama is deploying this for real life data.

2025-02-10 12:29 UTC, bwplotka commented
/prombench main --bench.version=bench/protofirst

2025-02-11 08:37 UTC, krajorama requested changes
awesome work! there's some nits and I'd like one function name change for clarity plz

2025-02-11 08:37 UTC, krajorama commented on prompb/io/prometheus/client/decoder.go
> +// NewMetricStreamingDecoder returns Go iterator that unmarshals given protobuf bytes one
```suggestion
// NewMetricStreamingDecoder returns a Go iterator that unmarshals given protobuf bytes one
```

2025-02-11 08:37 UTC, krajorama commented on prompb/io/prometheus/client/decoder.go
> +func parseLabels(dAtA []byte, b *labels.ScratchBuilder) error {
At first I was confused due to the name and the fact that it has a for loop inside, but the `b.Add()` bit is outside the loop.

```suggestion
func parseLabel(dAtA []byte, b *labels.ScratchBuilder) error {
```

2025-02-11 08:43 UTC, krajorama commented
> @krajorama is deploying this for real life data.

I've deployed it into a dev environment where we scrape around 7M metrics and keep around 400K for this test. At first let it run for 6h without native histograms or protobuf enabled. Then enabled native histograms and updated all scrape configs to have `always_scrape_classic_histograms: true`. Verified that I have both native histograms and classic histograms. The change was around 23:13 UTC.

CPU:
![image](https://github.com/user-attachments/assets/4c1a6b81-5dec-4a69-b07d-417aae1a8f4b)


Memory:
![image](https://github.com/user-attachments/assets/22f7fbba-aef9-4f1d-a667-055e0fc40172)

2025-02-11 10:08 UTC, bwplotka commented
With both having protobuf enabled:

Allocs and CPU much better:

![image](https://github.com/user-attachments/assets/ec0c8865-107c-4eed-9338-87c37d353fc7)

![image](https://github.com/user-attachments/assets/e6380de5-2489-4472-b862-768185d7b2ee)

Unfortunately I see max alloc 1GB heap higher, although profiles suggest otherwise. 🤔 

![image](https://github.com/user-attachments/assets/2a024240-102b-40d8-8c26-908122341830)

PR: https://pprof.me/a031b96b04f650a3fb5e6cb15947151c/?profileType=profile%3Ainuse_space%3Abytes%3Aspace%3Abytes&color_by=filename

![image](https://github.com/user-attachments/assets/9b68e789-5ff8-4ee7-843e-ab1d59c993af)

main: https://pprof.me/d33cba21047d414f6d8c6fb6c2922328/?profileType=profile%3Ainuse_space%3Abytes%3Aspace%3Abytes&color_by=filename

![image](https://github.com/user-attachments/assets/b564a2dd-0faf-4f79-99e4-bbe3ccb48fb4)

2025-02-11 10:56 UTC, bwplotka commented
I would say RSS is kind of similar, interesting. I think it's fine to merge and proceed, there's improvement in CPU.

![image](https://github.com/user-attachments/assets/e9e2353f-2db1-4db0-a876-f978f73d4358)

2025-02-11 10:57 UTC, bwplotka commented
/prombench cancel

2025-02-11 11:00 UTC, bwplotka commented
Thanks, applied your suggestions!

2025-02-11 12:22 UTC, krajorama approved these changes
LGTM.

2025-02-11 14:28 UTC, bboreham reviewed
Very good overall, but I have some comments.

2025-02-11 14:28 UTC, bboreham commented on model/textparse/protobufparse.go
> +	return yoloString(p.seriesBytes.Bytes())
This is unsafe.  Since nobody is using it, perhaps just return "" ?
Alternatively the docstring should say not to retain it, or go further and remove the return value (as you commented).

2025-02-11 14:28 UTC, bboreham commented on model/textparse/protobufparse.go
> +	return p.seriesBytes.Bytes(), []byte(p.dec.GetUnit())
Does seriesBytes fulfill the expectation of the caller?
I think it's expecting a metric name.

2025-02-11 14:28 UTC, bboreham commented on model/textparse/protobufparse.go
> +			// https://github.com/prometheus/prometheus/pull/15731/files/308d6301f3a4adf38164bd629621155c32183b4f#diff-6514f82c033f3a6d3ce48dae99e090260c0798c49a6e6c895ebbf96a583dd386
This URL does not find anything for me.

2025-02-11 14:28 UTC, bboreham commented on model/textparse/protobufparse.go
> +// * p.seriesBytes (copy).
What is meant by "copy" here?  `lset` ends up using a buffer in `p.builder`, and `seriesBytes` will re-use its own buffer.

2025-02-11 14:28 UTC, bboreham commented on prompb/io/prometheus/client/decoder.go
> +func (m *MetricStreamingDecoder) resetMetric() {
Suggest to add docstring, e.g. 
```
// reset all the fields in m to equal the zero value, but re-using slice memory.
```

2025-02-11 14:28 UTC, bboreham commented on model/textparse/protobufparse.go
> +	return p.seriesBytes.Bytes(), nil, v
Speculation, for future investigation: can we use `dec.mData` here?

2025-02-11 14:28 UTC, bboreham commented on prompb/io/prometheus/client/decoder.go
> +	m.mfData = b[varIntLength:totalLength] // TODO: Copy and reuse slice.
I didn't follow this TODO.  Why do we want to copy?

2025-02-11 14:28 UTC, bboreham commented on prompb/io/prometheus/client/decoder.go
> +	panic("don't use GetLabel, use Labels instead")
There is no method called `Labels`.

2025-02-11 15:26 UTC, bwplotka commented on model/textparse/protobufparse.go
> +	return p.seriesBytes.Bytes(), []byte(p.dec.GetUnit())
It's a metric name in this buffer for units. Maybe I should rename to `buf` then or so (:

2025-02-11 15:29 UTC, bwplotka commented on model/textparse/protobufparse.go
> +	return p.seriesBytes.Bytes(), nil, v
Yes, I want to unpack this later. I think we can just you might miss cache when switching protocols in the single scrape loop (is this possible? e.g.  same target negotiating different things). This might leak memory then.

We might need some handling for this case, otherwise this would allow us to NOT parse labels on every scrape for cache hits.

2025-02-12 07:38 UTC, bwplotka commented on model/textparse/protobufparse.go
> +	return yoloString(p.seriesBytes.Bytes())
Fair, changing `Metric` method in https://github.com/prometheus/prometheus/pull/16012

2025-02-12 08:18 UTC, bwplotka commented on prompb/io/prometheus/client/decoder.go
> +	m.mfData = b[varIntLength:totalLength] // TODO: Copy and reuse slice.
This is due to this sub slice referencing whole metric family buffer. If one would use it e.g. as a cache key or even label strings it would keep the whole memory down.

I will remove this suggestion, I think it's ok here -- the moment we use it as labels to be appended in DB or add a cache key we HAVE to copy and not reuse this anyway. I am concerned with the interface though - it's not very clear what can be reused, what's not, but that's to clean/document later.

2025-02-12 08:21 UTC, bwplotka commented on prompb/io/prometheus/client/decoder.go
> +func (m *MetricStreamingDecoder) Label(b *labels.ScratchBuilder) error {
Added comment for now.

2025-02-12 08:22 UTC, bwplotka commented
Rebased on top of https://github.com/prometheus/prometheus/pull/16012 otherwise good to go cc @bboreham - thanks for amazing review! 💪🏽

2025-02-12 09:02 UTC, bwplotka commented
/prombench main --bench.version=bench/cross-feature/protofirst

2025-02-12 09:08 UTC, bwplotka commented on model/textparse/protobufparse.go
> +	return p.seriesBytes.Bytes(), nil, v
Playing with this idea, but the blocker might be the fact that [proto serialization is not canonical](https://protobuf.dev/programming-guides/serialization-not-canonical/#:~:text=Unfortunately%2C%20protobuf%20serialization%20is%20not,of%20proto%20serialization%20as%20unstable.)

2025-02-12 09:13 UTC, bwplotka commented on model/textparse/protobufparse.go
> +	return p.seriesBytes.Bytes(), nil, v
Some options:

a) We only need "canonical" stability per scrape target. We can build guards e.g. another map from labels hash to cache key to remove duplicate entries. This will handle case of switching content type in the same target life time.
b) We add to proto hash (identity) and ask clients to give us this
c) We spend CPU to parse proto first for hash/cache key, then parse that to labels only if needed.

2025-02-12 13:42 UTC, bwplotka commented
## Summary

The current state: 
### Microbenchmarks from https://github.com/prometheus/prometheus/pull/15731#issuecomment-2647627751 are still valid. 

Protobuf parsing is:
* 15-40% faster (lower CPU time)
* Allocates ~60% less memory.
* Allocates 2x-700x less objects in memory.
* **It's the fastest (CPU time) scrape protocol now (~6% faster than PromText and OMText)**
* **It's allocating ~30% memory than other protocols.**

### Macrobenchmarks from https://github.com/prometheus/prometheus/pull/15731#issuecomment-2647848417 and https://github.com/prometheus/prometheus/pull/15731#issuecomment-2653052343

* Slightly more allocs/s vs OpenMetrics Text
![image](https://github.com/user-attachments/assets/b4d65c53-5b1c-4059-8baa-a52e0b5f0c9a)

* Slightly higher CPU use vs OpenMetrics text (although significantly lower than proto parsing without this optimization on main). This is likely due to higher allocs/s (GC overhead).

![image](https://github.com/user-attachments/assets/26338faa-38a8-46db-9808-b40920e5eb0f)

* RSS on par or lower:

![image](https://github.com/user-attachments/assets/57de3de5-15fe-479f-b504-1ec6c69da023)

### Next steps

I propose we cache more in https://github.com/prometheus/prometheus/pull/16020 (more complex, this PR can be merged safely without #16020 )

2025-02-12 13:42 UTC, bwplotka commented
/prombench cancel

2025-02-12 17:29 UTC, bboreham commented on model/textparse/protobufparse.go
> +	return p.seriesBytes.Bytes(), nil, v
I think the only problem with missing the cache is the stats for metrics get incremented. Same thing happens if you reorder labels in text format (there is an issue about this).

2025-02-12 17:31 UTC, bboreham approved these changes
Let’s give it a go.

2025-02-13 09:42 UTC, bboreham approved these changes

2025-02-13 09:42 UTC, bboreham commented on model/textparse/protobufparse.go
>  // It returns the string from which the metric was parsed.
This comment now out of date.

2025-02-13 10:21 UTC, bwplotka commented on model/textparse/protobufparse.go
>  // It returns the string from which the metric was parsed.
```suggestion
```

2025-02-13 10:25 UTC, bwplotka commented
/prombench main --bench.version=bench/protofirst

2025-02-13 10:38 UTC, merged