tsdb: drain any remaining actors in wal.
prometheus/prometheus pull request #7697
Opened 2020-07-30 10:14 UTC by johncming

The deprecated `wal` implementations have a situation that causes goroutine leak.

The PR has relation with another PR https://github.com/prometheus/prometheus/pull/7655#issuecomment-666016301

The leak bug result like
```
=== Failed
=== FAIL: tsdb  (0.00s)
PASS
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 15483 in state chan send, with github.com/prometheus/prometheus/tsdb.(*SegmentWAL).cut.func2 on top of the stack:
goroutine 15483 [chan send]:
github.com/prometheus/prometheus/tsdb.(*SegmentWAL).cut.func2(0xc0000be210)
	/home/circleci/project/tsdb/wal.go:599 +0xc0
created by github.com/prometheus/prometheus/tsdb.(*SegmentWAL).cut
	/home/circleci/project/tsdb/wal.go:598 +0x160
]
FAIL	github.com/prometheus/prometheus/tsdb	174.747s

DONE 1022 tests, 17 skipped, 1 failure in 379.805s
make: *** [Makefile.common:172: common-test] Error 1

Exited with code exit status 2
```

2020-08-26 09:47 UTC, codesome approved these changes
LGTM with 1 comment

2020-08-26 09:47 UTC, codesome commented on tsdb/wal.go
> +			f()
Let us log this error like below.

2020-08-26 09:54 UTC, johncming commented on tsdb/wal.go
> +			f()
OK. I will add it.

2020-08-26 10:14 UTC, codesome requested changes
Sorry, I take my LGTM back. If it was possible to add a function to the actor after stopping (even though we are draining it already before exiting), then it is possible that function will be added to the actor even after `close(w.actorc)`, hence cause a panic. We should actually reject WAL Logging after closing, but this doesn't eliminate the mentioned race as a WAL Logging could be on-going.

I don't have a way to fix this on top of my mind.

2020-08-26 11:47 UTC, johncming commented
> Sorry, I take my LGTM back. If it was possible to add a function to the actor after stopping (even though we are draining it already before exiting), then it is possible that function will be added to the actor even after `close(w.actorc)`, hence cause a panic. We should actually reject WAL Logging after closing, but this doesn't eliminate the mentioned race as a WAL Logging could be on-going.
> 
> I don't have a way to fix this on top of my mind.

Sorry. This PR can't solve the leak.  And close the channel in receiver goroutine will lead to panic. 

Since it has been marked as deprecated, I try to eliminate leak with minimal changes.

2020-09-21 16:19 UTC, roidelapluie commented
cc @codesome can we close this pull request? Thanks!

2020-10-28 11:54 UTC, bwplotka commented
Is this still reproducible? Let's reopen and start new PR if this happens again :hugs:

2020-10-28 11:54 UTC, closed without merging