Add hashmod relabeling test with hasmod and a newline
prometheus/prometheus pull request #8523
Opened 2021-02-19 10:27 UTC by roidelapluie

Currently hashmod hashes all the labels, even if there is a newline. To
ensure it still works in the future, let's add a test.

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

2021-02-19 10:38 UTC, roidelapluie commented
Note: this is implemented to catch a regression that could be introduced by #8520

2021-02-19 14:24 UTC, beorn7 requested changes
Otherwise LGTM

2021-02-19 14:24 UTC, beorn7 commented on pkg/relabel/relabel_test.go
> +			if cfg.Regex == emptyRegex {
```suggestion
			if cfg.Regex.original == "" {
```

2021-03-02 22:01 UTC, roidelapluie commented on pkg/relabel/relabel_test.go
> +			if cfg.Regex == emptyRegex {
Addressed

2021-03-03 12:39 UTC, beorn7 approved these changes

2021-03-03 21:09 UTC, merged