tests: Move from t.Errorf and others.
prometheus/prometheus pull request #9298
Opened 2021-09-04 12:44 UTC by Creatone

Fixes #8063.

2021-09-06 22:01 UTC, roidelapluie approved these changes
Thanks, this must have taken a lot of time!

I have added a few comments.

May I recommend you to split this into multiple pull requests? Maybe 4-5 small packages per pull request (files) ? It will be easier to review and we can merge them incrementally.

2021-09-06 22:01 UTC, roidelapluie requested changes
Sorry, I did not want to mark this as approved yet.

2021-09-07 18:24 UTC, Creatone commented
@roidelapluie No problem :)

2021-09-07 19:05 UTC, Creatone commented
@roidelapluie I'm sorry for the force push, I forgot to sign revert commits.

2021-09-08 09:54 UTC, Creatone commented
@roidelapluie Hope this split is enough.

2021-09-15 11:13 UTC, Creatone commented on web/api/v1/api_test.go
> +	ar.testing = m.testing
Because `ar.AlertingRules()` needs it.

2023-08-15 11:54 UTC, beorn7 commented
Running into this during our bug scrub. @roidelapluie it looks like your comments were all addressed, but you never commented on this again. Are you fine with it in general? If yes, then this needs a rebase. @Creatone would you still be willing to do that? Sorry for the long radio silence.

2024-01-23 11:47 UTC, bboreham commented
No update for 6 months; I will assign to myself and try to bring it up to date.

2024-02-01 14:28 UTC, bboreham commented
I rebased, squashed reverts and corrections, fixed up all the tests to pass, and updated a number of cases which are now flagged by the testify linter.
I also made a few simplifications to match what I think was the original intent of the test.

Personally I would not bother updating a plain `t.Fatal()` to `require.Fail()`, since the benefits are very slim, but I left those that were in this PR.

2024-02-01 14:52 UTC, beorn7 commented
@bboreham do you want another Prometheus maintainer to review this? If you feel comfortable with the current state, I would say just merge it. But happy to do another pass over it if you prefer.

2024-02-01 14:56 UTC, bboreham commented
Yes, it's possible I mangled something and I am not the best person to detect that. 
However I am ok to merge it now.  I will need to dismiss @roidelapluie's "requested changes" review.

2024-02-04 15:27 UTC, merged