Move packages out of deprecated pkg directory
prometheus/prometheus pull request #9478
Opened 2021-10-08 18:20 UTC by beorn7

Alternatively or in addition to #9477, I have taken action and just moved all packages out of the deprecated `pkg`.

This creates a new `model` directory and moves all data-model related
packages over there:
`exemplar labels relabel rulefmt textparse timestamp value`

All the others are more or less utilities and have been moved to `util`:
`gate logging modetimevfs pool runtime`

2021-10-13 12:09 UTC, beorn7 commented
Suggestion for the announcement mail:

"""
Dear Prometheus developers,

On 2021-08-22, the Prometheus dev summit has expressed a consensus to deprecate the `pkg` directory.

The `pkg` directory is used in some (but not all) repositories in the Prometheus GH org as a root directory for some (but not necessarily all) Go packages in a repository. The discussion of the pros and cons is nuanced (see the notes and recording of the dev summit), but the outcome is that we desire consistency between repositories and want to gravitate towards _not_ using the `pkg` directory. Please do not add more packages to any existing `pkg` directory, and move packages out of the directory at your convenience.

We plan to do the latter soon for prometheus/prometheus, and this mail intends to be a heads-up for those using the affected packages as libraries from outside the prometheus/prometheus repository.

The packages `gate`, `logging`, `modtimevfs`,  `pool`, and `runtime` will be moved to the (already existing) `util` directory.

The packages `exemplar`, `labels`, `relabel`, `rulefmt`, `textparse`, `timestamp`, and `value` will be moved to the (newly created) `model` directory.

It will happen in this pull request: https://github.com/prometheus/prometheus/pull/9478

Apologies for any hassle this may cause and thank you very much for your understanding,
"""

2021-10-13 14:00 UTC, roidelapluie commented
:+1:

2021-10-14 12:07 UTC, roidelapluie commented
> Mail has been set out: https://groups.google.com/g/prometheus-developers/c/M2wV7yc59Qs
> 
> How long should we wait before actually doing the move?

My suggestion is to do it when 2.31.0 is merged back to main.

2021-10-14 12:11 UTC, beorn7 commented
Fine with me.

2021-10-18 21:29 UTC, LeviHarrison commented
I think the top-level package `template` might also fit better into `model`.

2021-11-01 18:29 UTC, beorn7 commented
> I think the top-level package template might also fit better into model.

Maybe. But let's do other moves after this is merged.

I will now recreate this PR with @roidelapluie 's script.

2021-11-01 18:31 UTC, beorn7 commented
No, wait, release-2.31 hasn't been merged back into main, so I'll wait for the release to happen.

2021-11-08 14:41 UTC, beorn7 commented
I have now recreated the move on top of main, using @roidelapluie 's script. But I had to do a few extra steps in the parser code and for MS Windows.

2021-11-08 14:57 UTC, beorn7 commented
Script hasn't done pkg/rulefmt/testdata/* move, either.

2021-11-08 21:02 UTC, roidelapluie approved these changes
LGTM

2021-11-08 21:23 UTC, roidelapluie commented on pkg/textparse/README.md
> -# Making changes to textparse lexers
Where is this file gone?

2021-11-08 21:24 UTC, roidelapluie requested changes
Some files seem to be missing (there is more than the one I highlighted)

2021-11-08 21:24 UTC, roidelapluie commented on pkg/textparse/openmetricslex.l
> -%{
Where is this file gone?

2021-11-08 21:24 UTC, roidelapluie commented on pkg/textparse/promtestdata.nometa.txt
> -go_gc_duration_seconds{quantile="0"} 4.9351e-05
Where is this file gone?

2021-11-08 21:28 UTC, roidelapluie commented
All missing files are from the same directory.

2021-11-08 22:42 UTC, beorn7 commented
Yeah, the script missed a bunch of files, and then I tried to find them all, but failed with a few. Thanks for your attention

2021-11-08 22:42 UTC, beorn7 commented
I hope I got them all now.

2021-11-08 22:52 UTC, roidelapluie commented
![168/168 files reviewed](https://user-images.githubusercontent.com/291750/140830832-62638675-58ea-4864-89f9-c8baf9f63371.png)

I think so :)

2021-11-08 22:52 UTC, roidelapluie approved these changes
LGTM

2021-11-09 07:03 UTC, beorn7 commented
I did a whitespace commit to trigger the tests again. Some didn't run, for some reason.

2021-11-09 07:20 UTC, roidelapluie commented
It was probably unluckily at the same time I added oauth restrictions, just before I authorize circle CI again.

2021-11-09 09:51 UTC, roidelapluie approved these changes

2021-11-09 10:09 UTC, merged