Optimise VectorAnd for step invariant expression
prometheus/prometheus pull request #9577
Opened 2021-10-24 06:31 UTC by darshanime

closes https://github.com/prometheus/prometheus/issues/9368
Signed-off-by: darshanime <deathbullet@gmail.com>

2021-10-26 04:46 UTC, codesome reviewed
Thanks! Could you please benchmark this change to see it in action? You might need additional test cases in existing benchmark if it does not exist yet.

2021-10-30 12:49 UTC, darshanime commented
benchmarks look great for the somewhat contrived queries: 

```
rate(a_X[1m] @ start()) or rate(a_X[1m])
rate(a_X[1m]) unless rate(a_X[1m] @ start())
```

but good overall too...

<details>
  <summary>see benchmark</summary>

```
benchmark                                                                                                              old ns/op       new ns/op       delta
BenchmarkRangeQuery/expr=topk(1,_a_hundred),steps=10-12                                                                1331415         521372          -60.84%
BenchmarkRangeQuery/expr=topk(1,_a_hundred),steps=1-12                                                                 1130721         456700          -59.61%
BenchmarkRangeQuery/expr=rate(a_one[1m])_+_rate(b_one[1m]),steps=100-12                                                255612          104772          -59.01%
BenchmarkRangeQuery/expr=rate(a_ten[1m])_+_rate(b_ten[1m]),steps=1-12                                                  323835          133848          -58.67%
BenchmarkRangeQuery/expr=rate(a_one[1m])_+_rate(b_one[1m]),steps=10-12                                                 97785           40514           -58.57%
BenchmarkRangeQuery/expr=topk(1,_a_hundred),steps=100-12                                                               3563958         1479771         -58.48%
BenchmarkRangeQuery/expr=rate(a_hundred[1m])_+_rate(b_hundred[1m]),steps=1-12                                          2789163         1175406         -57.86%
BenchmarkRangeQuery/expr=rate(a_one[1m])_+_rate(b_one[1m]),steps=1-12                                                  81503           34572           -57.58%
BenchmarkRangeQuery/expr=topk(1,_a_hundred),steps=1000-12                                                              20807437        8878912         -57.33%
BenchmarkRangeQuery/expr=rate(a_one[1m])_+_rate(b_one[1m]),steps=1000-12                                               1594136         683827          -57.10%
BenchmarkRangeQuery/expr=rate(a_ten[1m])_+_rate(b_ten[1m]),steps=100-12                                                2104084         913280          -56.59%
BenchmarkRangeQuery/expr=topk(1,_a_one),steps=10-12                                                                    64319           28382           -55.87%
BenchmarkRangeQuery/expr=rate(a_ten[1m])_+_rate(b_ten[1m]),steps=10-12                                                 461107          204123          -55.73%
BenchmarkRangeQuery/expr=topk(1,_a_ten),steps=1000-12                                                                  3597283         1594170         -55.68%
BenchmarkRangeQuery/expr=topk(1,_a_one),steps=1-12                                                                     48018           21350           -55.54%
BenchmarkRangeQuery/expr=rate(a_hundred[1m])_+_rate(b_hundred[1m]),steps=10-12                                         4237556         1896584         -55.24%
BenchmarkRangeQuery/expr=rate(a_ten[1m])_+_rate(b_ten[1m]),steps=1000-12                                               16528192        7411697         -55.16%
BenchmarkRangeQuery/expr=sum_without_(l)(rate(a_one[1m])),steps=10-12                                                  74637           33590           -55.00%
BenchmarkRangeQuery/expr=topk(1,_a_ten),steps=10-12                                                                    163954          74059           -54.83%
BenchmarkRangeQuery/expr=topk(1,_a_one),steps=100-12                                                                   218469          101818          -53.39%
BenchmarkRangeQuery/expr=topk(1,_a_ten),steps=100-12                                                                   488831          232907          -52.35%
BenchmarkRangeQuery/expr=topk(1,_a_ten),steps=1-12                                                                     126252          60326           -52.22%
BenchmarkRangeQuery/expr=topk(1,_a_one),steps=1000-12                                                                  1689980         814135          -51.83%
BenchmarkRangeQuery/expr=rate(a_hundred[1m])_+_rate(b_hundred[1m]),steps=1000-12                                       169512531       82276697        -51.46%
BenchmarkRangeQuery/expr=rate(a_hundred[1m])_+_rate(b_hundred[1m]),steps=100-12                                        19777856        9711314         -50.90%
BenchmarkRangeQuery/expr=sum_without_(l)(rate(a_one[1m])),steps=100-12                                                 209459          105420          -49.67%
BenchmarkRangeQuery/expr=sum_without_(l)(rate(a_one[1m])),steps=1-12                                                   51078           26715           -47.70%
BenchmarkRangeQuery/expr=sum_without_(l)(rate(a_one[1m])),steps=1000-12                                                1401361         782545          -44.16%
BenchmarkRangeQuery/expr=sum_without_(l)(rate(a_ten[1m])),steps=1-12                                                   125267          71963           -42.55%
BenchmarkRangeQuery/expr=sum_without_(l)(rate(a_ten[1m])),steps=10-12                                                  157815          92847           -41.17%
BenchmarkRangeQuery/expr=sum_without_(l)(rate(a_ten[1m])),steps=100-12                                                 555043          335455          -39.56%
BenchmarkRangeQuery/expr=rate(a_hundred[1m])_unless_rate(a_hundred[1m]_@_start()),steps=1000-12                        33423683        20669163        -38.16%
BenchmarkRangeQuery/expr=sum_without_(l)(rate(a_ten[1m])),steps=1000-12                                                3897947         2423183         -37.83%
BenchmarkRangeQuery/expr=sum_without_(l)(rate(a_hundred[1m])),steps=1-12                                               776183          516819          -33.42%
BenchmarkRangeQuery/expr=sum_without_(l)(rate(a_hundred[1m])),steps=10-12                                              981640          670158          -31.73%
BenchmarkRangeQuery/expr=rate(a_ten[1m])_unless_rate(a_ten[1m]_@_start()),steps=1000-12                                3064840         2096917         -31.58%
BenchmarkRangeQuery/expr=rate(a_hundred[1m])_unless_rate(a_hundred[1m]_@_start()),steps=100-12                         4550706         3194092         -29.81%
BenchmarkRangeQuery/expr=rate(a_hundred[1m]_@_start())_or_rate(a_hundred[1m]),steps=1000-12                            54877943        38812508        -29.27%
BenchmarkRangeQuery/expr=sum_without_(l)(rate(a_hundred[1m])),steps=100-12                                             3573897         2534818         -29.07%
BenchmarkRangeQuery/expr=rate(a_hundred[1m]_@_start())_or_rate(a_hundred[1m]),steps=100-12                             6919438         5002720         -27.70%
BenchmarkRangeQuery/expr=count_values('value',_h_hundred),steps=1000-12                                                14321695705     10440053725     -27.10%
BenchmarkRangeQuery/expr=rate(a_ten[1m])_unless_rate(a_ten[1m]_@_start()),steps=100-12                                 477834          351528          -26.43%
BenchmarkRangeQuery/expr=rate(a_one[1m])_and_topk(1,_rate(a_one[1m]_@_start())),steps=1000-12                          586308          442876          -24.46%
BenchmarkRangeQuery/expr=sum_without_(l)(rate(a_hundred[1m])),steps=1000-12                                            24637059        18831991        -23.56%
BenchmarkRangeQuery/expr=rate(a_ten[1m]_@_start())_or_rate(a_ten[1m]),steps=1000-12                                    4924171         3776317         -23.31%
BenchmarkRangeQuery/expr=rate(a_ten[1m]_@_start())_or_rate(a_ten[1m]),steps=100-12                                     678841          523893          -22.83%
BenchmarkRangeQuery/expr=rate(a_ten[1m])_and_topk(1,_rate(a_ten[1m]_@_start())),steps=1-12                             172382          133898          -22.32%
BenchmarkRangeQuery/expr=rate(a_ten[1m])_and_topk(1,_rate(a_ten[1m]_@_start())),steps=1000-12                          2655246         20702 [...]

2023-08-15 11:39 UTC, beorn7 commented
@codesome (and maybe @bboreham ), we have run into this during the bug scrub, and it seems to us this is kind-of good to go. Would you agree? Of course, by now, it needs a rebase. @darshanime would you be able to do that?

2023-12-24 04:02 UTC, agoode commented
If I understand it correctly, this kind of optimization would be very helpful for Home Assistant users, since the current method for filtering out unavailable values is very expensive and needs a recorded rule to be efficient.

https://www.home-assistant.io/integrations/prometheus/#metrics-in-unavailable-or-unknown-states

2024-01-28 19:50 UTC, darshanime commented
rebased. relevant benchmarks

```
go test -bench=BenchmarkRangeQuery -run=- -count 5 | tee main
go test -bench=BenchmarkRangeQuery -run=- -count 5 | tee optimize_joins
benchstat main optimize_joins
```

<details>
  <summary>see benchmark</summary>

```
$ benchstat main optimize_joins
goos: darwin
goarch: arm64
pkg: github.com/prometheus/prometheus/promql
                                                                                             │     main      │           optimize_joins            │
                                                                                             │    sec/op     │    sec/op     vs base               │
RangeQuery/expr=rate(a_one[1m])_and_topk(1,_rate(a_one[1m]_@_start())),steps=1-10               21.16µ ± ∞ ¹   21.87µ ± ∞ ¹   +3.35% (p=0.016 n=5)
RangeQuery/expr=rate(a_one[1m])_and_topk(1,_rate(a_one[1m]_@_start())),steps=100-10             44.69µ ± ∞ ¹   45.12µ ± ∞ ¹        ~ (p=0.222 n=5)
RangeQuery/expr=rate(a_one[1m])_and_topk(1,_rate(a_one[1m]_@_start())),steps=1000-10            226.3µ ± ∞ ¹   219.6µ ± ∞ ¹   -2.98% (p=0.008 n=5)
RangeQuery/expr=rate(a_ten[1m])_and_topk(1,_rate(a_ten[1m]_@_start())),steps=1-10               60.72µ ± ∞ ¹   62.41µ ± ∞ ¹   +2.77% (p=0.008 n=5)
RangeQuery/expr=rate(a_ten[1m])_and_topk(1,_rate(a_ten[1m]_@_start())),steps=100-10             169.1µ ± ∞ ¹   172.6µ ± ∞ ¹        ~ (p=0.056 n=5)
RangeQuery/expr=rate(a_ten[1m])_and_topk(1,_rate(a_ten[1m]_@_start())),steps=1000-10            1.007m ± ∞ ¹   1.004m ± ∞ ¹        ~ (p=0.690 n=5)
RangeQuery/expr=rate(a_hundred[1m])_and_topk(1,_rate(a_hundred[1m]_@_start())),steps=1-10       442.7µ ± ∞ ¹   448.0µ ± ∞ ¹   +1.21% (p=0.008 n=5)
RangeQuery/expr=rate(a_hundred[1m])_and_topk(1,_rate(a_hundred[1m]_@_start())),steps=100-10     1.376m ± ∞ ¹   1.405m ± ∞ ¹   +2.08% (p=0.008 n=5)
RangeQuery/expr=rate(a_hundred[1m])_and_topk(1,_rate(a_hundred[1m]_@_start())),steps=1000-10    8.398m ± ∞ ¹   8.735m ± ∞ ¹   +4.02% (p=0.032 n=5)
RangeQuery/expr=rate(a_one[1m]_@_start())_or_rate(a_one[1m]),steps=1-10                         17.83µ ± ∞ ¹   17.93µ ± ∞ ¹        ~ (p=0.095 n=5)
RangeQuery/expr=rate(a_one[1m]_@_start())_or_rate(a_one[1m]),steps=100-10                       40.92µ ± ∞ ¹   40.57µ ± ∞ ¹        ~ (p=0.397 n=5)
RangeQuery/expr=rate(a_one[1m]_@_start())_or_rate(a_one[1m]),steps=1000-10                      215.4µ ± ∞ ¹   213.8µ ± ∞ ¹   -0.74% (p=0.008 n=5)
RangeQuery/expr=rate(a_ten[1m]_@_start())_or_rate(a_ten[1m]),steps=1-10                         58.80µ ± ∞ ¹   60.49µ ± ∞ ¹   +2.88% (p=0.008 n=5)
RangeQuery/expr=rate(a_ten[1m]_@_start())_or_rate(a_ten[1m]),steps=100-10                       254.5µ ± ∞ ¹   225.8µ ± ∞ ¹  -11.28% (p=0.008 n=5)
RangeQuery/expr=rate(a_ten[1m]_@_start())_or_rate(a_ten[1m]),steps=1000-10                      1.888m ± ∞ ¹   1.616m ± ∞ ¹  -14.39% (p=0.008 n=5)
RangeQuery/expr=rate(a_hundred[1m]_@_start())_or_rate(a_hundred[1m]),steps=1-10                 477.3µ ± ∞ ¹   497.7µ ± ∞ ¹   +4.27% (p=0.008 n=5)
RangeQuery/expr=rate(a_hundred[1m]_@_start())_or_rate(a_hundred[1m]),steps=100-10               2.893m ± ∞ ¹   2.113m ± ∞ ¹  -26.94% (p=0.008 n=5)
RangeQuery/expr=rate(a_hundred[1m]_@_start())_or_rate(a_hundred[1m]),steps=1000-10              23.75m ± ∞ ¹   15.66m ± ∞ ¹  -34.07% (p=0.008 n=5)
RangeQuery/expr=rate(a_one[1m])_unless_rate(a_one[1m]_@_start()),steps=1-10                     17.80µ ± ∞ ¹   17.72µ ± ∞ ¹        ~ (p=0.841 n=5)
RangeQuery/expr=rate(a_one[1m])_unless_rate(a_one[1m]_@_start()),steps=100-10                   36.31µ ± ∞ ¹   36.38µ ± ∞ ¹        ~ (p=1.000 n=5)
RangeQuery/expr=rate(a_one[1m])_unless_rate(a_one[1m]_@_start()),steps=1000-10                  174.1µ ± ∞ ¹   176.0µ ± ∞ ¹        ~ (p=0.151 n=5)
RangeQuery/expr=rate(a_ten[1m])_unless_rate(a_ten[1m]_@_start()),steps=1-10                     57.02µ ± ∞ ¹   57.70µ ± ∞ ¹        ~ (p=0.056 n=5)
RangeQuery/expr=rate(a_ten[1m])_unless_rate(a_ten[1m]_@_start()),steps=100-10                   199.2µ ± ∞ ¹   169.3µ ± ∞ ¹  -15.05% (p=0.008 n=5)
RangeQuery/expr=rate(a_ten[1m])_unless_rate(a_ten[1m]_@_start()),steps=1000-10                  1.346m ± ∞ ¹   1.030m ± ∞ ¹  -23.44% (p=0.008 n=5)
RangeQuery/expr=rate(a_hundred[1m])_unless_rate(a_hundred[1m]_@_start()),steps=1-10             453.3µ ± ∞ ¹   453.3µ ± ∞ ¹        ~ (p=1.000 n=5)
RangeQuery/expr=rate(a_hundred[1m])_unless_rate(a_hundred[1m]_@_start()),steps=100-10           2.261m ± ∞ ¹   1.509m ± ∞ ¹  -33.27% (p=0.008 n=5)
RangeQuery/expr=rate(a_hundred[1m])_unless_rate(a_hundred[1m]_@_start()),steps=1000-10         17.333m ± ∞ ¹   9.947m ± ∞ ¹  -42.61% (p=0.008 n=5)
geomean                                                                                         321.7µ         296.7µ         -7.78%
¹ need >= 6 samples for confidence interval at level 0.95

                                                                                             │      main       │            optimize_joins            │
                                                                                             │      B/op       │     B/op       vs base               │
RangeQuery/expr=rate(a_one[1m])_and_topk(1,_rate(a_one[1m]_@_start())),steps=1-10                19.48Ki ± ∞ ¹   19.93Ki ± ∞ ¹   +2.33% (p=0.008 n=5)
RangeQuery/expr=rate(a_one[1m])_and_topk(1,_rate(a_one[1m]_@_start())),steps=100-10              28.86Ki ± ∞ ¹   29.32Ki ± ∞ ¹   +1.57% (p=0.008 n=5)
RangeQuery/expr=rate(a_one[1m])_and_topk(1,_rate(a_one[1m]_@_start())),steps=1000-10             122.4Ki ± ∞ ¹   122.9Ki ± ∞ ¹   +0.38% (p=0.008 n=5)
RangeQuery/expr=rate(a_ten[1m])_and_topk(1,_rate(a_ten[1m]_@_start())),steps=1-10                39.41Ki ± ∞ ¹   39.86Ki ± ∞ ¹   +1.15% (p=0.008 n=5)
RangeQuery/expr=rate(a_ten[1m])_and_topk(1,_rate(a_ten[1m]_@_start())),steps=100-10              53.71Ki ± ∞ ¹   54.17Ki ± ∞ ¹   +0.85% (p=0.008 n=5)
RangeQuery/expr=rate(a_ten[1m])_and_topk(1,_rate(a_ten[1m]_@_start())),steps=1000-10             169.8Ki ± ∞ ¹   170.2Ki ± ∞ ¹   +0.26% (p=0.008 n=5)
RangeQuery/expr=rate(a_hundred[1m])_and_topk(1,_rate(a_hundred[1m]_@_start())),steps=1-10        256.3Ki ± ∞ ¹   256.8Ki ± ∞ ¹   +0.18% (p=0.008 n=5)
RangeQuery/expr=rate(a_hundred[1m])_and_topk(1,_rate(a_hundred[1m]_@_start())),steps=100-10      318.2Ki ± ∞ ¹   318.7Ki ± ∞ ¹   +0.16% (p=0.008 n=5)
RangeQuery/expr=rate(a_hundred[1m])_and_topk(1,_rate(a_hundred[1m]_@_start())),steps=1000-10     654.1Ki ± ∞ ¹   654.5Ki ± ∞ ¹   +0.06% (p=0.008 n=5)
RangeQuery/expr=rate(a_one[1m]_@_start())_or_rate(a_one[1m]),steps=1-10                          16.16Ki ± ∞ ¹   16.51Ki ± ∞ ¹   +2.13% (p=0.008 n=5)
RangeQuery/expr=rate(a_one[1m]_@_start())_or_rate(a_one[1m]),steps=100-10                        21.61Ki ± ∞ ¹   21.95Ki ± ∞ ¹   +1.60% (p=0.008 n=5)
RangeQuery/expr=rate(a_one[1m]_@_start())_or_rate(a_one[1m]),steps=1000-10                       69.85Ki ± ∞ ¹   70.20Ki ± ∞ ¹   +0.51% (p=0.008 n=5)
RangeQuery/expr=rate(a_ten[1m]_@_start())_or_rate(a_ten[1m]),steps=1-10                          35.32Ki ± ∞ ¹   35.38Ki ± ∞ ¹   +0.16% (p=0.008 n=5)
RangeQuery/expr=rate(a_ten[1m]_@_start())_or_rate(a_ten[1m]),steps=100-10                        73.86Ki ± ∞ ¹   45.75Ki ± ∞ ¹  -38.06% (p=0.008 n=5)
RangeQuery/expr=rate(a_ten[1m]_@_start())_or_rate(a_ten[1m]),steps=1000-10                       400.7Ki ± ∞ ¹   116.6Ki ± ∞ ¹  -70.91% (p=0.008 n=5)
RangeQuery/expr=rate(a_hundred[1m]_@_start())_or_rate(a_hundred[1m]),steps=1-10                  251.9Ki ± ∞ ¹   242.1Ki ± ∞ ¹   -3.93% (p=0.008 n=5)
RangeQuery/expr=rate(a_hundred[1m]_@_start())_or_rate(a_hundred[1m]),steps=100-10               1321.0Ki ± ∞ ¹   299.9Ki ± ∞ ¹  -77.30% (p=0.008 n=5)
RangeQuery/expr=rate(a_hundred[1m]_@_start())_or_rate(a_hundred[1m]),steps=1000-10             10797.5Ki ± ∞ ¹   590.9Ki ± ∞ ¹  -94.53% (p=0.008 n=5)
RangeQuery/expr=rate(a_one[1m])_unless_rate(a_one[1m]_@_start()),steps=1-10                      16.10Ki ± ∞ ¹   16.44Ki ± ∞ ¹   +2.14% (p=0.008 n=5)
RangeQuery/expr=rate(a_one[1m] [...]

2024-03-06 11:52 UTC, bboreham reviewed
Thanks for this.  I think the idea is valid, but I'm afraid I could not understand the code.

Suggest adding some comments explaining key features.

2024-03-06 11:52 UTC, bboreham commented on promql/engine.go
> +		stepInvariantSigSet: make([]map[string]struct{}, len(exprs)),
Do we need to allocate in every case?

2024-03-06 11:52 UTC, bboreham commented on promql/engine.go
> +			}
I got lost here.  Why are we looping?

2024-05-01 17:19 UTC, darshanime reviewed
@bboreham ptal, i think i've addressed all your comments.

2024-05-13 17:07 UTC, bboreham reviewed
Progress: I now think I understand this PR a bit.

I made a few comments below; one of them suggests an error, which if I'm right implies you should add a test for that case.

Could we do the same for `VectorBinop` ?  I notice there is a `rightSigs` already, although it is currently only for re-use of memory.

2024-05-13 17:07 UTC, bboreham commented on promql/engine.go
> +	case enh.stepInvariantSigSet[1] != nil:
Is it possible that both sides are step-invariant?

2024-10-08 11:54 UTC, bboreham commented
Hello from the bug-scrub!

Looks like no update since this PR was reviewed in May; do you think you will come back to it @darshanime ?

2025-01-04 03:31 UTC, darshanime commented on promql/engine.go
> +	case enh.stepInvariantSigSet[1] != nil:
added a case for that

2025-01-04 10:02 UTC, darshanime commented on promql/engine.go
> +			}
i don't see how it could be done outside of the range-values loop

2025-01-04 10:03 UTC, darshanime commented on promql/engine.go
> +		vectors = rhs
good catch, i've added a test case now

2025-01-04 11:55 UTC, darshanime commented
@bboreham i have rebased and addressed your comments. 

> Could we do the same for VectorBinop ?

i'd like to do that in a separate pr if that's okay with you

2025-03-04 11:33 UTC, beorn7 commented
Hello again from the bug-scrub! 

@bboreham are you able to continue the review on this?

2025-06-05 14:43 UTC, bboreham requested changes
I apologise it took me a really long time to get back to this.
It also took me a long time to pin down a problem.  I still feel the code is hard to understand, but that could be acceptable.

However it doesn't always pass its own tests.

```
go test -count=20 -run=TestEvaluations/testdata/operators.test//@ ./promql
--- FAIL: TestEvaluations (0.08s)
    --- FAIL: TestEvaluations/testdata/operators.test (0.08s)
        --- FAIL: TestEvaluations/testdata/operators.test/line_17/vector_matching_a_@_start()_and_vector_matching_b (0.00s)
            test.go:1122: 
                        Error Trace:    /home/bryan/src/github.com/prometheus/prometheus/promql/promqltest/test.go:1122
                        Error:          Received unexpected error:
                                        error in eval vector_matching_a @ start() and vector_matching_b (line 17): expected metric {__name__="vector_matching_a", l="x"} not found
                        Test:           TestEvaluations/testdata/operators.test/line_17/vector_matching_a_@_start()_and_vector_matching_b
        --- FAIL: TestEvaluations/testdata/operators.test/line_20/vector_matching_a_@_end()_and_vector_matching_b (0.00s)
            test.go:1122: 
                        Error Trace:    /home/bryan/src/github.com/prometheus/prometheus/promql/promqltest/test.go:1122
                        Error:          Received unexpected error:
                                        error in eval vector_matching_a @ end() and vector_matching_b (line 20): expected metric {__name__="vector_matching_a", l="x"} not found
                        Test:           TestEvaluations/testdata/operators.test/line_20/vector_matching_a_@_end()_and_vector_matching_b
```

I also tried reversing the new tests, and got a different failure:

```
eval range from 0 to 30m step 5m vector_matching_b and vector_matching_a @ start()
	vector_matching_b{l="x"} 0 4 8 12 16 20 24

eval range from 0 to 30m step 5m vector_matching_b and vector_matching_a @ end()
	vector_matching_b{l="x"} 0 4 8 12 16 20 24

eval range from 0 to 30m step 5m vector_matching_b @ end() and vector_matching_a
	vector_matching_b{l="x"} 24 24 24 24 24 24 24

eval range from 0 to 30m step 5m vector_matching_b @ start() and vector_matching_a @ end()
	vector_matching_b{l="x"} 0 0 0 0 0 0 0
```

```
        --- FAIL: TestEvaluations/testdata/operators.test/line_35/vector_matching_b_@_end()_and_vector_matching_a (0.00s)
            test.go:1122: 
                        Error Trace:    /home/bryan/src/github.com/prometheus/prometheus/promql/promqltest/test.go:1122
                        Error:          Received unexpected error:
                                        error evaluating query "vector_matching_b @ end() and vector_matching_a" (line 35): unexpected error: runtime error: index out of range [1] with length 1
                        Test:           TestEvaluations/testdata/operators.test/line_35/vector_matching_b_@_end()_and_vector_matching_a
```

2025-08-26 11:56 UTC, bboreham commented
Hello again from the bug-scrub!

@darshanime this is with you to fix the inconsistent test results.

2026-01-06 11:57 UTC, bboreham commented
Hello again from the bug-scrub!

@darshanime do you think you will come back to this?

2026-05-12 11:47 UTC, bboreham commented
Closing due to lack of response.  Happy to re-open if you come back to it @darshanime.

2026-05-12 11:47 UTC, closed without merging