Temp dir
prometheus/prometheus pull request #9641
Opened 2021-11-02 09:37 UTC by praveenghuge

Related to #9594
small PR to fix tsdb directory

2021-11-02 20:35 UTC, roidelapluie commented
Can you please rebase this pull request? thank you

2021-11-05 15:17 UTC, codesome requested changes
Thanks for this PR! We have to fix few erroneous changes before we can merge :)

2021-11-05 15:17 UTC, codesome commented on tsdb/db_test.go
> +	require.NoError(t, nil)
We should not ignore the error here. You can have `var err error` before the `if` and check the error.

2021-11-05 15:17 UTC, codesome commented on tsdb/db_test.go
> -	require.NoError(t, db.Close())
Removed by mistake?

2021-11-05 15:17 UTC, codesome commented on tsdb/querier_test.go
> +				require.NoError(b, nil)
You can remove this line now

2023-08-15 11:08 UTC, closed without merging

2023-12-05 15:10 UTC, beorn7 commented
FTR: @milencium wants to work on #9594, which might be based on this PR or might be a complete restart.