WIP: Log time series for out-of-order samples in remote write receiver
prometheus/prometheus pull request #9894
Opened 2021-11-29 16:33 UTC by rabenhorst

2021-12-01 09:09 UTC, codesome requested changes
This seems to be doing same thing twice. You can have `switch errors.Cause(err) {` in `ServeHTTP` instead of `switch err {` that is already there with the additional fields that you have added in the log.

2021-12-02 08:49 UTC, rabenhorst commented
> This seems to be doing same thing twice. You can have `switch errors.Cause(err) {` in `ServeHTTP` instead of `switch err {` that is already there with the additional fields that you have added in the log.

Yes, but there I don't have the details of the out-of-order sample and can't log it. The idea is to log the sample that caused the out-of-order error for better debugging.

2021-12-06 10:14 UTC, codesome reviewed
Oh right, missed that part. Could you please inline `logAppendError()` where it's called? Since it's a single place, feels unnecessary to have it separated.

2021-12-06 16:14 UTC, rabenhorst commented
> Oh right, missed that part. Could you please inline `logAppendError()` where it's called? Since it's a single place, feels unnecessary to have it separated.
Done.

2021-12-07 14:23 UTC, codesome commented on storage/remote/write_handler.go
> +				level.Error(h.logger).Log("msg", "Out of order sample from remote write", "err", err.Error(), "series", labels.String(), "timestamp", s.Timestamp)
```suggestion
			switch errors.Cause(err) {
			case storage.ErrOutOfOrderSample, storage.ErrOutOfBounds, storage.ErrDuplicateSampleForTimestamp:
				level.Error(h.logger).Log("msg", "Out of order sample from remote write", "err", err.Error(), "series", labels.String(), "timestamp", s.Timestamp)
			}
```

2021-12-08 08:49 UTC, rabenhorst commented
Sry may bad only copied half the code. Should be fixed now.

2021-12-08 14:53 UTC, codesome approved these changes

2021-12-08 15:07 UTC, merged

2021-12-29 13:08 UTC, maxpain commented
When it will be released?